/* Generated by scripts/build_static_exercise_guides.py. Do not edit manually. */
import gobletSquat01Setup from './goblet-squat-01-setup.jpg'
import gobletSquat02Drive from './goblet-squat-02-drive.jpg'
import gobletSquat03Finish from './goblet-squat-03-finish.jpg'
import dumbbellFrontSquat01Setup from './dumbbell-front-squat-01-setup.jpg'
import dumbbellFrontSquat02Drive from './dumbbell-front-squat-02-drive.jpg'
import dumbbellFrontSquat03Finish from './dumbbell-front-squat-03-finish.jpg'
import bodyweightSquat01Setup from './bodyweight-squat-01-setup.jpg'
import bodyweightSquat02Drive from './bodyweight-squat-02-drive.jpg'
import bodyweightSquat03Finish from './bodyweight-squat-03-finish.jpg'
import prisonerSquat01Setup from './prisoner-squat-01-setup.jpg'
import prisonerSquat02Drive from './prisoner-squat-02-drive.jpg'
import prisonerSquat03Finish from './prisoner-squat-03-finish.jpg'
import standingWallCalfRaise01Setup from './standing-wall-calf-raise-01-setup.jpg'
import standingWallCalfRaise02Drive from './standing-wall-calf-raise-02-drive.jpg'
import standingWallCalfRaise03Finish from './standing-wall-calf-raise-03-finish.jpg'
import dumbbellRomanianDeadlift01Setup from './dumbbell-romanian-deadlift-01-setup.jpg'
import dumbbellRomanianDeadlift02Drive from './dumbbell-romanian-deadlift-02-drive.jpg'
import dumbbellRomanianDeadlift03Finish from './dumbbell-romanian-deadlift-03-finish.jpg'
import dumbbellDeadlift01Setup from './dumbbell-deadlift-01-setup.jpg'
import dumbbellDeadlift02Drive from './dumbbell-deadlift-02-drive.jpg'
import dumbbellDeadlift03Finish from './dumbbell-deadlift-03-finish.jpg'
import bodyweightHipHinge01Setup from './bodyweight-hip-hinge-01-setup.jpg'
import bodyweightHipHinge02Drive from './bodyweight-hip-hinge-02-drive.jpg'
import bodyweightHipHinge03Finish from './bodyweight-hip-hinge-03-finish.jpg'
import gluteBridgeExercise01Setup from './glute-bridge-exercise-01-setup.jpg'
import gluteBridgeExercise02Lift from './glute-bridge-exercise-02-lift.jpg'
import dumbbellBenchPress01Setup from './dumbbell-bench-press-01-setup.jpg'
import dumbbellBenchPress02Drive from './dumbbell-bench-press-02-drive.jpg'
import dumbbellBenchPress03Finish from './dumbbell-bench-press-03-finish.jpg'
import dumbbellFloorPress01Setup from './dumbbell-floor-press-01-setup.jpg'
import dumbbellFloorPress02Drive from './dumbbell-floor-press-02-drive.jpg'
import dumbbellFloorPress03Finish from './dumbbell-floor-press-03-finish.jpg'
import inclinePushUp01Setup from './incline-push-up-01-setup.jpg'
import inclinePushUp02Drive from './incline-push-up-02-drive.jpg'
import inclinePushUp03Finish from './incline-push-up-03-finish.jpg'
import bentKneePushUp01Setup from './bent-knee-push-up-01-setup.jpg'
import bentKneePushUp02Lower from './bent-knee-push-up-02-lower.jpg'
import pushUp01Setup from './push-up-01-setup.jpg'
import pushUp02Drive from './push-up-02-drive.jpg'
import pushUp03Finish from './push-up-03-finish.jpg'
import wallPushUp01Setup from './wall-push-up-01-setup.jpg'
import wallPushUp02Drive from './wall-push-up-02-drive.jpg'
import wallPushUp03Finish from './wall-push-up-03-finish.jpg'
import seatedCableRow01Setup from './seated-cable-row-01-setup.jpg'
import seatedCableRow02Drive from './seated-cable-row-02-drive.jpg'
import seatedCableRow03Finish from './seated-cable-row-03-finish.jpg'
import cableHighRow01Setup from './cable-high-row-01-setup.jpg'
import cableHighRow02Drive from './cable-high-row-02-drive.jpg'
import cableHighRow03Finish from './cable-high-row-03-finish.jpg'
import cableSingleArmRow01Setup from './cable-single-arm-row-01-setup.jpg'
import cableSingleArmRow02Drive from './cable-single-arm-row-02-drive.jpg'
import cableSingleArmRow03Finish from './cable-single-arm-row-03-finish.jpg'
import oneArmDumbbellRow01Setup from './one-arm-dumbbell-row-01-setup.jpg'
import oneArmDumbbellRow02Drive from './one-arm-dumbbell-row-02-drive.jpg'
import oneArmDumbbellRow03Finish from './one-arm-dumbbell-row-03-finish.jpg'
import dumbbellOverheadPress01Setup from './dumbbell-overhead-press-01-setup.jpg'
import dumbbellOverheadPress02Drive from './dumbbell-overhead-press-02-drive.jpg'
import dumbbellOverheadPress03Finish from './dumbbell-overhead-press-03-finish.jpg'
import seatedDumbbellPress01Setup from './seated-dumbbell-press-01-setup.jpg'
import seatedDumbbellPress02Drive from './seated-dumbbell-press-02-drive.jpg'
import seatedDumbbellPress03Finish from './seated-dumbbell-press-03-finish.jpg'
import singleArmDumbbellPress01Setup from './single-arm-dumbbell-press-01-setup.jpg'
import singleArmDumbbellPress02Drive from './single-arm-dumbbell-press-02-drive.jpg'
import singleArmDumbbellPress03Finish from './single-arm-dumbbell-press-03-finish.jpg'
import dumbbellLateralRaise01Setup from './dumbbell-lateral-raise-01-setup.jpg'
import dumbbellLateralRaise02Drive from './dumbbell-lateral-raise-02-drive.jpg'
import dumbbellLateralRaise03Finish from './dumbbell-lateral-raise-03-finish.jpg'
import singleArmDumbbellLateralRaise01Setup from './single-arm-dumbbell-lateral-raise-01-setup.jpg'
import singleArmDumbbellLateralRaise02Drive from './single-arm-dumbbell-lateral-raise-02-drive.jpg'
import singleArmDumbbellLateralRaise03Finish from './single-arm-dumbbell-lateral-raise-03-finish.jpg'
import cableLateralRaise01Setup from './cable-lateral-raise-01-setup.jpg'
import cableLateralRaise02Drive from './cable-lateral-raise-02-drive.jpg'
import cableLateralRaise03Finish from './cable-lateral-raise-03-finish.jpg'
import dumbbellBicepsCurl01Setup from './dumbbell-biceps-curl-01-setup.jpg'
import dumbbellBicepsCurl02Drive from './dumbbell-biceps-curl-02-drive.jpg'
import dumbbellBicepsCurl03Finish from './dumbbell-biceps-curl-03-finish.jpg'
import dumbbellHammerCurl01Setup from './dumbbell-hammer-curl-01-setup.jpg'
import dumbbellHammerCurl02Drive from './dumbbell-hammer-curl-02-drive.jpg'
import dumbbellHammerCurl03Finish from './dumbbell-hammer-curl-03-finish.jpg'
import cableBicepsCurl01Setup from './cable-biceps-curl-01-setup.jpg'
import cableBicepsCurl02Drive from './cable-biceps-curl-02-drive.jpg'
import cableBicepsCurl03Finish from './cable-biceps-curl-03-finish.jpg'
import cableTricepsPushdown01Setup from './cable-triceps-pushdown-01-setup.jpg'
import cableTricepsPushdown02Drive from './cable-triceps-pushdown-02-drive.jpg'
import cableTricepsPushdown03Finish from './cable-triceps-pushdown-03-finish.jpg'
import dumbbellOverheadTricepsExtension01Setup from './dumbbell-overhead-triceps-extension-01-setup.jpg'
import dumbbellOverheadTricepsExtension02Drive from './dumbbell-overhead-triceps-extension-02-drive.jpg'
import dumbbellOverheadTricepsExtension03Finish from './dumbbell-overhead-triceps-extension-03-finish.jpg'
import dumbbellLyingTricepsExtension01Setup from './dumbbell-lying-triceps-extension-01-setup.jpg'
import dumbbellLyingTricepsExtension02Drive from './dumbbell-lying-triceps-extension-02-drive.jpg'
import dumbbellLyingTricepsExtension03Finish from './dumbbell-lying-triceps-extension-03-finish.jpg'
import dumbbellReverseFly01Setup from './dumbbell-reverse-fly-01-setup.jpg'
import dumbbellReverseFly02Drive from './dumbbell-reverse-fly-02-drive.jpg'
import dumbbellReverseFly03Finish from './dumbbell-reverse-fly-03-finish.jpg'
import cableReverseFly01Setup from './cable-reverse-fly-01-setup.jpg'
import cableReverseFly02Drive from './cable-reverse-fly-02-drive.jpg'
import cableReverseFly03Finish from './cable-reverse-fly-03-finish.jpg'
import cableFacePull01Setup from './cable-face-pull-01-setup.jpg'
import cableFacePull02Drive from './cable-face-pull-02-drive.jpg'
import cableFacePull03Finish from './cable-face-pull-03-finish.jpg'
import dumbbellShrug01Setup from './dumbbell-shrug-01-setup.jpg'
import dumbbellShrug02Drive from './dumbbell-shrug-02-drive.jpg'
import dumbbellShrug03Finish from './dumbbell-shrug-03-finish.jpg'
import cableShrug01Setup from './cable-shrug-01-setup.jpg'
import cableShrug02Drive from './cable-shrug-02-drive.jpg'
import cableShrug03Finish from './cable-shrug-03-finish.jpg'
import machineShrug01Setup from './machine-shrug-01-setup.jpg'
import machineShrug02Drive from './machine-shrug-02-drive.jpg'
import machineShrug03Finish from './machine-shrug-03-finish.jpg'
import latPulldown01Setup from './lat-pulldown-01-setup.jpg'
import latPulldown02Drive from './lat-pulldown-02-drive.jpg'
import latPulldown03Finish from './lat-pulldown-03-finish.jpg'
import cableStraightArmPulldown01Setup from './cable-straight-arm-pulldown-01-setup.jpg'
import cableStraightArmPulldown02Drive from './cable-straight-arm-pulldown-02-drive.jpg'
import cableStraightArmPulldown03Finish from './cable-straight-arm-pulldown-03-finish.jpg'
import neutralGripPulldown01Setup from './neutral-grip-pulldown-01-setup.jpg'
import neutralGripPulldown02Drive from './neutral-grip-pulldown-02-drive.jpg'
import neutralGripPulldown03Finish from './neutral-grip-pulldown-03-finish.jpg'
import proneWRaise01Setup from './prone-w-raise-01-setup.jpg'
import proneWRaise02Drive from './prone-w-raise-02-drive.jpg'
import proneWRaise03Finish from './prone-w-raise-03-finish.jpg'
import proneYRaise01Setup from './prone-y-raise-01-setup.jpg'
import proneYRaise02Drive from './prone-y-raise-02-drive.jpg'
import proneYRaise03Finish from './prone-y-raise-03-finish.jpg'
import floorProneCobra01Setup from './floor-prone-cobra-01-setup.jpg'
import floorProneCobra02Lift from './floor-prone-cobra-02-lift.jpg'
import contralateralLimbRaise01Setup from './contralateral-limb-raise-01-setup.jpg'
import contralateralLimbRaise02Raise from './contralateral-limb-raise-02-raise.jpg'
import deadBug01Setup from './dead-bug-01-setup.jpg'
import deadBug02Extend from './dead-bug-02-extend.jpg'
import deadBug03Control from './dead-bug-03-control.jpg'
import deadBug04Finish from './dead-bug-04-finish.jpg'
import birdDog01Setup from './bird-dog-01-setup.jpg'
import birdDog02Extend from './bird-dog-02-extend.jpg'
import birdDog03Control from './bird-dog-03-control.jpg'
import birdDog04Finish from './bird-dog-04-finish.jpg'
import plank01Setup from './plank-01-setup.jpg'
import plank02Hold from './plank-02-hold.jpg'
import smithFlatBenchPress01Setup from './smith-flat-bench-press-01-setup.jpg'
import smithFlatBenchPress02Drive from './smith-flat-bench-press-02-drive.jpg'
import smithFlatBenchPress03Finish from './smith-flat-bench-press-03-finish.jpg'
import inclineDumbbellBenchPress3001Setup from './incline-dumbbell-bench-press-30-01-setup.jpg'
import inclineDumbbellBenchPress3002Drive from './incline-dumbbell-bench-press-30-02-drive.jpg'
import inclineDumbbellBenchPress3003Finish from './incline-dumbbell-bench-press-30-03-finish.jpg'
import seatedMachineShoulderPress01Setup from './seated-machine-shoulder-press-01-setup.jpg'
import seatedMachineShoulderPress02Drive from './seated-machine-shoulder-press-02-drive.jpg'
import seatedMachineShoulderPress03Finish from './seated-machine-shoulder-press-03-finish.jpg'
import leaningPecDeckFly01Setup from './leaning-pec-deck-fly-01-setup.jpg'
import leaningPecDeckFly02Drive from './leaning-pec-deck-fly-02-drive.jpg'
import leaningPecDeckFly03Finish from './leaning-pec-deck-fly-03-finish.jpg'
import machineSeatedRow01Setup from './machine-seated-row-01-setup.jpg'
import machineSeatedRow02Drive from './machine-seated-row-02-drive.jpg'
import machineSeatedRow03Finish from './machine-seated-row-03-finish.jpg'
import reversePecDeckFly01Setup from './reverse-pec-deck-fly-01-setup.jpg'
import reversePecDeckFly02Drive from './reverse-pec-deck-fly-02-drive.jpg'
import reversePecDeckFly03Finish from './reverse-pec-deck-fly-03-finish.jpg'
import smithSquat01Setup from './smith-squat-01-setup.jpg'
import smithSquat02Drive from './smith-squat-02-drive.jpg'
import smithSquat03Finish from './smith-squat-03-finish.jpg'
import seatedLegPress01Setup from './seated-leg-press-01-setup.jpg'
import seatedLegPress02Drive from './seated-leg-press-02-drive.jpg'
import seatedLegPress03Finish from './seated-leg-press-03-finish.jpg'
import dumbbellReverseLunge01Setup from './dumbbell-reverse-lunge-01-setup.jpg'
import dumbbellReverseLunge02Drive from './dumbbell-reverse-lunge-02-drive.jpg'
import dumbbellReverseLunge03Finish from './dumbbell-reverse-lunge-03-finish.jpg'
import seatedLegExtension01Setup from './seated-leg-extension-01-setup.jpg'
import seatedLegExtension02Drive from './seated-leg-extension-02-drive.jpg'
import seatedLegExtension03Finish from './seated-leg-extension-03-finish.jpg'
import machineCrunch01Setup from './machine-crunch-01-setup.jpg'
import machineCrunch02Drive from './machine-crunch-02-drive.jpg'
import machineCrunch03Finish from './machine-crunch-03-finish.jpg'
import inclineDumbbellFly01Setup from './incline-dumbbell-fly-01-setup.jpg'
import inclineDumbbellFly02Drive from './incline-dumbbell-fly-02-drive.jpg'
import inclineDumbbellFly03Finish from './incline-dumbbell-fly-03-finish.jpg'
import machineHipThrust01Setup from './machine-hip-thrust-01-setup.jpg'
import machineHipThrust02Drive from './machine-hip-thrust-02-drive.jpg'
import machineHipThrust03Finish from './machine-hip-thrust-03-finish.jpg'
import machineLegCurl01Setup from './machine-leg-curl-01-setup.jpg'
import machineLegCurl02Drive from './machine-leg-curl-02-drive.jpg'
import machineLegCurl03Finish from './machine-leg-curl-03-finish.jpg'
import machineHipAbduction01Setup from './machine-hip-abduction-01-setup.jpg'
import machineHipAbduction02Drive from './machine-hip-abduction-02-drive.jpg'
import machineHipAbduction03Finish from './machine-hip-abduction-03-finish.jpg'
import standingCalfRaise01Setup from './standing-calf-raise-01-setup.jpg'
import standingCalfRaise02Drive from './standing-calf-raise-02-drive.jpg'
import standingCalfRaise03Finish from './standing-calf-raise-03-finish.jpg'

export const staticGuidesByExerciseCode = {
  GOBLET_SQUAT: {
    primaryRef: "asset://exercise-guides/goblet-squat-01-setup.jpg",
    stages: [
      {
        id: "setup",
        label: "站稳",
        description: "脚掌稳定，负重靠近身体。",
        source: gobletSquat01Setup,
      },
      {
        id: "drive",
        label: "下蹲",
        description: "屈髋屈膝，膝盖跟随脚尖方向。",
        source: gobletSquat02Drive,
      },
      {
        id: "finish",
        label: "到位",
        description: "保持躯干稳定，在可控深度停住。",
        source: gobletSquat03Finish,
      },
    ],
  },
  DUMBBELL_FRONT_SQUAT: {
    primaryRef: "asset://exercise-guides/dumbbell-front-squat-01-setup.jpg",
    stages: [
      {
        id: "setup",
        label: "站稳",
        description: "脚掌稳定，负重靠近身体。",
        source: dumbbellFrontSquat01Setup,
      },
      {
        id: "drive",
        label: "下蹲",
        description: "屈髋屈膝，膝盖跟随脚尖方向。",
        source: dumbbellFrontSquat02Drive,
      },
      {
        id: "finish",
        label: "到位",
        description: "保持躯干稳定，在可控深度停住。",
        source: dumbbellFrontSquat03Finish,
      },
    ],
  },
  BODYWEIGHT_SQUAT: {
    primaryRef: "asset://exercise-guides/bodyweight-squat-01-setup.jpg",
    stages: [
      {
        id: "setup",
        label: "站稳",
        description: "脚掌稳定，负重靠近身体。",
        source: bodyweightSquat01Setup,
      },
      {
        id: "drive",
        label: "下蹲",
        description: "屈髋屈膝，膝盖跟随脚尖方向。",
        source: bodyweightSquat02Drive,
      },
      {
        id: "finish",
        label: "到位",
        description: "保持躯干稳定，在可控深度停住。",
        source: bodyweightSquat03Finish,
      },
    ],
  },
  PRISONER_SQUAT: {
    primaryRef: "asset://exercise-guides/prisoner-squat-01-setup.jpg",
    stages: [
      {
        id: "setup",
        label: "站稳",
        description: "双手轻放头后，脚掌稳定并保持胸口自然。",
        source: prisonerSquat01Setup,
      },
      {
        id: "drive",
        label: "下蹲",
        description: "屈髋屈膝，膝盖跟随脚尖方向。",
        source: prisonerSquat02Drive,
      },
      {
        id: "finish",
        label: "到位",
        description: "在躯干稳定的可控深度停住。",
        source: prisonerSquat03Finish,
      },
    ],
  },
  STANDING_WALL_CALF_RAISE: {
    primaryRef: "asset://exercise-guides/standing-wall-calf-raise-01-setup.jpg",
    stages: [
      {
        id: "setup",
        label: "脚跟落地",
        description: "双手轻扶墙面，双脚平行站稳。",
        source: standingWallCalfRaise01Setup,
      },
      {
        id: "drive",
        label: "提起脚跟",
        description: "缓慢抬起脚跟，把重心保持在前脚掌。",
        source: standingWallCalfRaise02Drive,
      },
      {
        id: "finish",
        label: "稳定顶端",
        description: "身体保持直立，再缓慢放下脚跟。",
        source: standingWallCalfRaise03Finish,
      },
    ],
  },
  DUMBBELL_ROMANIAN_DEADLIFT: {
    primaryRef: "asset://exercise-guides/dumbbell-romanian-deadlift-01-setup.jpg",
    stages: [
      {
        id: "setup",
        label: "站稳",
        description: "脚掌压稳，背部保持自然。",
        source: dumbbellRomanianDeadlift01Setup,
      },
      {
        id: "drive",
        label: "送髋",
        description: "髋部向后，负重贴近腿部。",
        source: dumbbellRomanianDeadlift02Drive,
      },
      {
        id: "finish",
        label: "到位",
        description: "大腿后侧有拉伸感时保持稳定。",
        source: dumbbellRomanianDeadlift03Finish,
      },
    ],
  },
  DUMBBELL_DEADLIFT: {
    primaryRef: "asset://exercise-guides/dumbbell-deadlift-01-setup.jpg",
    stages: [
      {
        id: "setup",
        label: "握稳",
        description: "哑铃靠近小腿，脚掌压稳并保持背部自然。",
        source: dumbbellDeadlift01Setup,
      },
      {
        id: "drive",
        label: "提起",
        description: "脚掌发力站起，负重持续贴近腿部。",
        source: dumbbellDeadlift02Drive,
      },
      {
        id: "finish",
        label: "站直",
        description: "髋膝伸直后稳定站立，避免身体后仰。",
        source: dumbbellDeadlift03Finish,
      },
    ],
  },
  BODYWEIGHT_HIP_HINGE: {
    primaryRef: "asset://exercise-guides/bodyweight-hip-hinge-01-setup.jpg",
    stages: [
      {
        id: "setup",
        label: "站稳",
        description: "脚掌压稳，背部保持自然。",
        source: bodyweightHipHinge01Setup,
      },
      {
        id: "drive",
        label: "送髋",
        description: "髋部向后，负重贴近腿部。",
        source: bodyweightHipHinge02Drive,
      },
      {
        id: "finish",
        label: "到位",
        description: "大腿后侧有拉伸感时保持稳定。",
        source: bodyweightHipHinge03Finish,
      },
    ],
  },
  GLUTE_BRIDGE_EXERCISE: {
    primaryRef: "asset://exercise-guides/glute-bridge-exercise-01-setup.jpg",
    stages: [
      {
        id: "setup",
        label: "仰卧准备",
        description: "双脚踩稳，屈膝并保持腰背自然。",
        source: gluteBridgeExercise01Setup,
      },
      {
        id: "lift",
        label: "抬髋",
        description: "臀部发力抬起髋部，避免腰部过度后仰。",
        source: gluteBridgeExercise02Lift,
      },
    ],
  },
  DUMBBELL_BENCH_PRESS: {
    primaryRef: "asset://exercise-guides/dumbbell-bench-press-01-setup.jpg",
    stages: [
      {
        id: "setup",
        label: "起始",
        description: "肩背和脚部先稳定支撑。",
        source: dumbbellBenchPress01Setup,
      },
      {
        id: "drive",
        label: "推起",
        description: "手腕稳定，沿可控路径推起负重。",
        source: dumbbellBenchPress02Drive,
      },
      {
        id: "finish",
        label: "完成",
        description: "手臂接近伸直，避免锁死关节。",
        source: dumbbellBenchPress03Finish,
      },
    ],
  },
  DUMBBELL_FLOOR_PRESS: {
    primaryRef: "asset://exercise-guides/dumbbell-floor-press-01-setup.jpg",
    stages: [
      {
        id: "setup",
        label: "起始",
        description: "肩背和脚部先稳定支撑。",
        source: dumbbellFloorPress01Setup,
      },
      {
        id: "drive",
        label: "推起",
        description: "手腕稳定，沿可控路径推起负重。",
        source: dumbbellFloorPress02Drive,
      },
      {
        id: "finish",
        label: "完成",
        description: "手臂接近伸直，避免锁死关节。",
        source: dumbbellFloorPress03Finish,
      },
    ],
  },
  INCLINE_PUSH_UP: {
    primaryRef: "asset://exercise-guides/incline-push-up-01-setup.jpg",
    stages: [
      {
        id: "setup",
        label: "支撑",
        description: "双手撑稳，身体保持一条直线。",
        source: inclinePushUp01Setup,
      },
      {
        id: "drive",
        label: "下降",
        description: "屈肘让胸口靠近支撑面。",
        source: inclinePushUp02Drive,
      },
      {
        id: "finish",
        label: "最低点",
        description: "核心收紧，不塌腰或耸肩。",
        source: inclinePushUp03Finish,
      },
    ],
  },
  BENT_KNEE_PUSH_UP: {
    primaryRef: "asset://exercise-guides/bent-knee-push-up-01-setup.jpg",
    stages: [
      {
        id: "setup",
        label: "跪姿支撑",
        description: "双手和双膝压稳，头背髋保持稳定。",
        source: bentKneePushUp01Setup,
      },
      {
        id: "lower",
        label: "控制下降",
        description: "屈肘降低身体，不塌腰或抬高臀部。",
        source: bentKneePushUp02Lower,
      },
    ],
  },
  PUSH_UP: {
    primaryRef: "asset://exercise-guides/push-up-01-setup.jpg",
    stages: [
      {
        id: "setup",
        label: "直臂支撑",
        description: "双手与双脚压稳，头背髋保持接近直线。",
        source: pushUp01Setup,
      },
      {
        id: "drive",
        label: "控制下降",
        description: "屈肘约四十五度，身体整体靠近地面。",
        source: pushUp02Drive,
      },
      {
        id: "finish",
        label: "最低点",
        description: "核心持续收紧，不塌腰或耸肩。",
        source: pushUp03Finish,
      },
    ],
  },
  WALL_PUSH_UP: {
    primaryRef: "asset://exercise-guides/wall-push-up-01-setup.jpg",
    stages: [
      {
        id: "setup",
        label: "扶墙支撑",
        description: "双手撑墙，双脚后移并让身体保持直线。",
        source: wallPushUp01Setup,
      },
      {
        id: "drive",
        label: "靠近墙面",
        description: "屈肘让胸口缓慢靠近墙面。",
        source: wallPushUp02Drive,
      },
      {
        id: "finish",
        label: "控制返回",
        description: "推回起点，避免耸肩或身体折叠。",
        source: wallPushUp03Finish,
      },
    ],
  },
  SEATED_CABLE_ROW: {
    primaryRef: "asset://exercise-guides/seated-cable-row-01-setup.jpg",
    stages: [
      {
        id: "setup",
        label: "伸臂",
        description: "躯干稳定，肩膀自然下沉。",
        source: seatedCableRow01Setup,
      },
      {
        id: "drive",
        label: "后拉",
        description: "肘部向后，肩胛向中间收拢。",
        source: seatedCableRow02Drive,
      },
      {
        id: "finish",
        label: "收紧",
        description: "握把靠近身体，避免大幅后仰。",
        source: seatedCableRow03Finish,
      },
    ],
  },
  CABLE_HIGH_ROW: {
    primaryRef: "asset://exercise-guides/cable-high-row-01-setup.jpg",
    stages: [
      {
        id: "setup",
        label: "伸臂",
        description: "躯干稳定，肩膀自然下沉。",
        source: cableHighRow01Setup,
      },
      {
        id: "drive",
        label: "后拉",
        description: "肘部向后，肩胛向中间收拢。",
        source: cableHighRow02Drive,
      },
      {
        id: "finish",
        label: "收紧",
        description: "握把靠近身体，避免大幅后仰。",
        source: cableHighRow03Finish,
      },
    ],
  },
  CABLE_SINGLE_ARM_ROW: {
    primaryRef: "asset://exercise-guides/cable-single-arm-row-01-setup.jpg",
    stages: [
      {
        id: "setup",
        label: "伸臂",
        description: "躯干稳定，肩膀自然下沉。",
        source: cableSingleArmRow01Setup,
      },
      {
        id: "drive",
        label: "后拉",
        description: "肘部向后，肩胛向中间收拢。",
        source: cableSingleArmRow02Drive,
      },
      {
        id: "finish",
        label: "收紧",
        description: "握把靠近身体，避免大幅后仰。",
        source: cableSingleArmRow03Finish,
      },
    ],
  },
  ONE_ARM_DUMBBELL_ROW: {
    primaryRef: "asset://exercise-guides/one-arm-dumbbell-row-01-setup.jpg",
    stages: [
      {
        id: "setup",
        label: "稳定支撑",
        description: "一手一膝压稳训练凳，负重手自然伸展。",
        source: oneArmDumbbellRow01Setup,
      },
      {
        id: "drive",
        label: "向后划船",
        description: "肘部朝髋部方向移动，躯干不要旋转。",
        source: oneArmDumbbellRow02Drive,
      },
      {
        id: "finish",
        label: "背部收紧",
        description: "哑铃靠近身体后停稳，再受控放下。",
        source: oneArmDumbbellRow03Finish,
      },
    ],
  },
  DUMBBELL_OVERHEAD_PRESS: {
    primaryRef: "asset://exercise-guides/dumbbell-overhead-press-01-setup.jpg",
    stages: [
      {
        id: "setup",
        label: "肩前",
        description: "核心收紧，负重稳定在肩部附近。",
        source: dumbbellOverheadPress01Setup,
      },
      {
        id: "drive",
        label: "推举",
        description: "沿头部两侧向上推，避免腰部后仰。",
        source: dumbbellOverheadPress02Drive,
      },
      {
        id: "finish",
        label: "顶端",
        description: "负重位于身体上方，肩颈保持放松。",
        source: dumbbellOverheadPress03Finish,
      },
    ],
  },
  SEATED_DUMBBELL_PRESS: {
    primaryRef: "asset://exercise-guides/seated-dumbbell-press-01-setup.jpg",
    stages: [
      {
        id: "setup",
        label: "肩前",
        description: "核心收紧，负重稳定在肩部附近。",
        source: seatedDumbbellPress01Setup,
      },
      {
        id: "drive",
        label: "推举",
        description: "沿头部两侧向上推，避免腰部后仰。",
        source: seatedDumbbellPress02Drive,
      },
      {
        id: "finish",
        label: "顶端",
        description: "负重位于身体上方，肩颈保持放松。",
        source: seatedDumbbellPress03Finish,
      },
    ],
  },
  SINGLE_ARM_DUMBBELL_PRESS: {
    primaryRef: "asset://exercise-guides/single-arm-dumbbell-press-01-setup.jpg",
    stages: [
      {
        id: "setup",
        label: "肩前",
        description: "核心收紧，负重稳定在肩部附近。",
        source: singleArmDumbbellPress01Setup,
      },
      {
        id: "drive",
        label: "推举",
        description: "沿头部两侧向上推，避免腰部后仰。",
        source: singleArmDumbbellPress02Drive,
      },
      {
        id: "finish",
        label: "顶端",
        description: "负重位于身体上方，肩颈保持放松。",
        source: singleArmDumbbellPress03Finish,
      },
    ],
  },
  DUMBBELL_LATERAL_RAISE: {
    primaryRef: "asset://exercise-guides/dumbbell-lateral-raise-01-setup.jpg",
    stages: [
      {
        id: "setup",
        label: "手臂下垂",
        description: "站稳并让手肘保持轻微弯曲。",
        source: dumbbellLateralRaise01Setup,
      },
      {
        id: "drive",
        label: "向侧面抬起",
        description: "肩部带动手臂平稳向两侧移动。",
        source: dumbbellLateralRaise02Drive,
      },
      {
        id: "finish",
        label: "肩部高度",
        description: "抬到肩部附近停稳，避免耸肩。",
        source: dumbbellLateralRaise03Finish,
      },
    ],
  },
  SINGLE_ARM_DUMBBELL_LATERAL_RAISE: {
    primaryRef: "asset://exercise-guides/single-arm-dumbbell-lateral-raise-01-setup.jpg",
    stages: [
      {
        id: "setup",
        label: "手臂下垂",
        description: "站稳并让手肘保持轻微弯曲。",
        source: singleArmDumbbellLateralRaise01Setup,
      },
      {
        id: "drive",
        label: "向侧面抬起",
        description: "肩部带动手臂平稳向两侧移动。",
        source: singleArmDumbbellLateralRaise02Drive,
      },
      {
        id: "finish",
        label: "肩部高度",
        description: "抬到肩部附近停稳，避免耸肩。",
        source: singleArmDumbbellLateralRaise03Finish,
      },
    ],
  },
  CABLE_LATERAL_RAISE: {
    primaryRef: "asset://exercise-guides/cable-lateral-raise-01-setup.jpg",
    stages: [
      {
        id: "setup",
        label: "手臂下垂",
        description: "站稳并让手肘保持轻微弯曲。",
        source: cableLateralRaise01Setup,
      },
      {
        id: "drive",
        label: "向侧面抬起",
        description: "肩部带动手臂平稳向两侧移动。",
        source: cableLateralRaise02Drive,
      },
      {
        id: "finish",
        label: "肩部高度",
        description: "抬到肩部附近停稳，避免耸肩。",
        source: cableLateralRaise03Finish,
      },
    ],
  },
  DUMBBELL_BICEPS_CURL: {
    primaryRef: "asset://exercise-guides/dumbbell-biceps-curl-01-setup.jpg",
    stages: [
      {
        id: "setup",
        label: "手臂下垂",
        description: "站稳并让上臂贴近身体。",
        source: dumbbellBicepsCurl01Setup,
      },
      {
        id: "drive",
        label: "屈肘举起",
        description: "固定上臂，用手臂前侧带动负重。",
        source: dumbbellBicepsCurl02Drive,
      },
      {
        id: "finish",
        label: "顶端停稳",
        description: "接近肩部后停稳，不用身体甩动。",
        source: dumbbellBicepsCurl03Finish,
      },
    ],
  },
  DUMBBELL_HAMMER_CURL: {
    primaryRef: "asset://exercise-guides/dumbbell-hammer-curl-01-setup.jpg",
    stages: [
      {
        id: "setup",
        label: "手臂下垂",
        description: "站稳并让上臂贴近身体。",
        source: dumbbellHammerCurl01Setup,
      },
      {
        id: "drive",
        label: "屈肘举起",
        description: "固定上臂，用手臂前侧带动负重。",
        source: dumbbellHammerCurl02Drive,
      },
      {
        id: "finish",
        label: "顶端停稳",
        description: "接近肩部后停稳，不用身体甩动。",
        source: dumbbellHammerCurl03Finish,
      },
    ],
  },
  CABLE_BICEPS_CURL: {
    primaryRef: "asset://exercise-guides/cable-biceps-curl-01-setup.jpg",
    stages: [
      {
        id: "setup",
        label: "手臂下垂",
        description: "站稳并让上臂贴近身体。",
        source: cableBicepsCurl01Setup,
      },
      {
        id: "drive",
        label: "屈肘举起",
        description: "固定上臂，用手臂前侧带动负重。",
        source: cableBicepsCurl02Drive,
      },
      {
        id: "finish",
        label: "顶端停稳",
        description: "接近肩部后停稳，不用身体甩动。",
        source: cableBicepsCurl03Finish,
      },
    ],
  },
  CABLE_TRICEPS_PUSHDOWN: {
    primaryRef: "asset://exercise-guides/cable-triceps-pushdown-01-setup.jpg",
    stages: [
      {
        id: "setup",
        label: "屈肘准备",
        description: "固定上臂，让手肘处于可控弯曲位置。",
        source: cableTricepsPushdown01Setup,
      },
      {
        id: "drive",
        label: "伸直手肘",
        description: "只移动前臂，避免身体借力。",
        source: cableTricepsPushdown02Drive,
      },
      {
        id: "finish",
        label: "手臂伸展",
        description: "在手肘接近伸直时停稳，不锁死关节。",
        source: cableTricepsPushdown03Finish,
      },
    ],
  },
  DUMBBELL_OVERHEAD_TRICEPS_EXTENSION: {
    primaryRef: "asset://exercise-guides/dumbbell-overhead-triceps-extension-01-setup.jpg",
    stages: [
      {
        id: "setup",
        label: "屈肘准备",
        description: "固定上臂，让手肘处于可控弯曲位置。",
        source: dumbbellOverheadTricepsExtension01Setup,
      },
      {
        id: "drive",
        label: "伸直手肘",
        description: "只移动前臂，避免身体借力。",
        source: dumbbellOverheadTricepsExtension02Drive,
      },
      {
        id: "finish",
        label: "手臂伸展",
        description: "在手肘接近伸直时停稳，不锁死关节。",
        source: dumbbellOverheadTricepsExtension03Finish,
      },
    ],
  },
  DUMBBELL_LYING_TRICEPS_EXTENSION: {
    primaryRef: "asset://exercise-guides/dumbbell-lying-triceps-extension-01-setup.jpg",
    stages: [
      {
        id: "setup",
        label: "屈肘准备",
        description: "固定上臂，让手肘处于可控弯曲位置。",
        source: dumbbellLyingTricepsExtension01Setup,
      },
      {
        id: "drive",
        label: "伸直手肘",
        description: "只移动前臂，避免身体借力。",
        source: dumbbellLyingTricepsExtension02Drive,
      },
      {
        id: "finish",
        label: "手臂伸展",
        description: "在手肘接近伸直时停稳，不锁死关节。",
        source: dumbbellLyingTricepsExtension03Finish,
      },
    ],
  },
  DUMBBELL_REVERSE_FLY: {
    primaryRef: "asset://exercise-guides/dumbbell-reverse-fly-01-setup.jpg",
    stages: [
      {
        id: "setup",
        label: "肩胛稳定",
        description: "站稳或俯身后先保持躯干稳定。",
        source: dumbbellReverseFly01Setup,
      },
      {
        id: "drive",
        label: "向外展开",
        description: "肘部向外移动，肩部不要耸起。",
        source: dumbbellReverseFly02Drive,
      },
      {
        id: "finish",
        label: "上背收紧",
        description: "肩部后侧和上背收紧后受控返回。",
        source: dumbbellReverseFly03Finish,
      },
    ],
  },
  CABLE_REVERSE_FLY: {
    primaryRef: "asset://exercise-guides/cable-reverse-fly-01-setup.jpg",
    stages: [
      {
        id: "setup",
        label: "肩胛稳定",
        description: "站稳或俯身后先保持躯干稳定。",
        source: cableReverseFly01Setup,
      },
      {
        id: "drive",
        label: "向外展开",
        description: "肘部向外移动，肩部不要耸起。",
        source: cableReverseFly02Drive,
      },
      {
        id: "finish",
        label: "上背收紧",
        description: "肩部后侧和上背收紧后受控返回。",
        source: cableReverseFly03Finish,
      },
    ],
  },
  CABLE_FACE_PULL: {
    primaryRef: "asset://exercise-guides/cable-face-pull-01-setup.jpg",
    stages: [
      {
        id: "setup",
        label: "肩胛稳定",
        description: "站稳或俯身后先保持躯干稳定。",
        source: cableFacePull01Setup,
      },
      {
        id: "drive",
        label: "向外展开",
        description: "肘部向外移动，肩部不要耸起。",
        source: cableFacePull02Drive,
      },
      {
        id: "finish",
        label: "上背收紧",
        description: "肩部后侧和上背收紧后受控返回。",
        source: cableFacePull03Finish,
      },
    ],
  },
  DUMBBELL_SHRUG: {
    primaryRef: "asset://exercise-guides/dumbbell-shrug-01-setup.jpg",
    stages: [
      {
        id: "setup",
        label: "肩部放松",
        description: "站稳并让双臂自然下垂。",
        source: dumbbellShrug01Setup,
      },
      {
        id: "drive",
        label: "垂直耸肩",
        description: "保持手肘伸展，将肩部垂直抬高。",
        source: dumbbellShrug02Drive,
      },
      {
        id: "finish",
        label: "顶端停稳",
        description: "肩部抬高后短暂停稳，不转动肩膀。",
        source: dumbbellShrug03Finish,
      },
    ],
  },
  CABLE_SHRUG: {
    primaryRef: "asset://exercise-guides/cable-shrug-01-setup.jpg",
    stages: [
      {
        id: "setup",
        label: "肩部放松",
        description: "站稳并让双臂自然下垂。",
        source: cableShrug01Setup,
      },
      {
        id: "drive",
        label: "垂直耸肩",
        description: "保持手肘伸展，将肩部垂直抬高。",
        source: cableShrug02Drive,
      },
      {
        id: "finish",
        label: "顶端停稳",
        description: "肩部抬高后短暂停稳，不转动肩膀。",
        source: cableShrug03Finish,
      },
    ],
  },
  MACHINE_SHRUG: {
    primaryRef: "asset://exercise-guides/machine-shrug-01-setup.jpg",
    stages: [
      {
        id: "setup",
        label: "肩部放松",
        description: "站稳并让双臂自然下垂。",
        source: machineShrug01Setup,
      },
      {
        id: "drive",
        label: "垂直耸肩",
        description: "保持手肘伸展，将肩部垂直抬高。",
        source: machineShrug02Drive,
      },
      {
        id: "finish",
        label: "顶端停稳",
        description: "肩部抬高后短暂停稳，不转动肩膀。",
        source: machineShrug03Finish,
      },
    ],
  },
  LAT_PULLDOWN: {
    primaryRef: "asset://exercise-guides/lat-pulldown-01-setup.jpg",
    stages: [
      {
        id: "setup",
        label: "伸展",
        description: "坐稳并保持胸廓自然。",
        source: latPulldown01Setup,
      },
      {
        id: "drive",
        label: "下拉",
        description: "肘部向下，握把朝上胸移动。",
        source: latPulldown02Drive,
      },
      {
        id: "finish",
        label: "收紧",
        description: "肩胛下沉，不把握把拉到颈后。",
        source: latPulldown03Finish,
      },
    ],
  },
  CABLE_STRAIGHT_ARM_PULLDOWN: {
    primaryRef: "asset://exercise-guides/cable-straight-arm-pulldown-01-setup.jpg",
    stages: [
      {
        id: "setup",
        label: "举臂",
        description: "手臂接近伸直，躯干保持稳定。",
        source: cableStraightArmPulldown01Setup,
      },
      {
        id: "drive",
        label: "下压",
        description: "以肩关节为轴向下压握把。",
        source: cableStraightArmPulldown02Drive,
      },
      {
        id: "finish",
        label: "到腿侧",
        description: "背部收紧，避免摆动借力。",
        source: cableStraightArmPulldown03Finish,
      },
    ],
  },
  NEUTRAL_GRIP_PULLDOWN: {
    primaryRef: "asset://exercise-guides/neutral-grip-pulldown-01-setup.jpg",
    stages: [
      {
        id: "setup",
        label: "伸展",
        description: "坐稳并保持胸廓自然。",
        source: neutralGripPulldown01Setup,
      },
      {
        id: "drive",
        label: "下拉",
        description: "肘部向下，握把朝上胸移动。",
        source: neutralGripPulldown02Drive,
      },
      {
        id: "finish",
        label: "收紧",
        description: "肩胛下沉，不把握把拉到颈后。",
        source: neutralGripPulldown03Finish,
      },
    ],
  },
  PRONE_W_RAISE: {
    primaryRef: "asset://exercise-guides/prone-w-raise-01-setup.jpg",
    stages: [
      {
        id: "setup",
        label: "俯卧",
        description: "颈部放松，额头轻靠支撑。",
        source: proneWRaise01Setup,
      },
      {
        id: "drive",
        label: "抬臂",
        description: "肩胛先稳定，再小幅抬起手臂。",
        source: proneWRaise02Drive,
      },
      {
        id: "finish",
        label: "收紧",
        description: "保持 W 或 Y 形，不耸肩。",
        source: proneWRaise03Finish,
      },
    ],
  },
  PRONE_Y_RAISE: {
    primaryRef: "asset://exercise-guides/prone-y-raise-01-setup.jpg",
    stages: [
      {
        id: "setup",
        label: "俯卧",
        description: "颈部放松，额头轻靠支撑。",
        source: proneYRaise01Setup,
      },
      {
        id: "drive",
        label: "抬臂",
        description: "肩胛先稳定，再小幅抬起手臂。",
        source: proneYRaise02Drive,
      },
      {
        id: "finish",
        label: "收紧",
        description: "保持 W 或 Y 形，不耸肩。",
        source: proneYRaise03Finish,
      },
    ],
  },
  FLOOR_PRONE_COBRA: {
    primaryRef: "asset://exercise-guides/floor-prone-cobra-01-setup.jpg",
    stages: [
      {
        id: "setup",
        label: "俯卧准备",
        description: "双臂放在身体两侧，颈部保持自然。",
        source: floorProneCobra01Setup,
      },
      {
        id: "lift",
        label: "收紧抬起",
        description: "肩胛轻轻收拢并小幅抬起上胸，不用腰部后仰借力。",
        source: floorProneCobra02Lift,
      },
    ],
  },
  CONTRALATERAL_LIMB_RAISE: {
    primaryRef: "asset://exercise-guides/contralateral-limb-raise-01-setup.jpg",
    stages: [
      {
        id: "setup",
        label: "俯卧准备",
        description: "手臂和双腿自然伸展，骨盆保持稳定。",
        source: contralateralLimbRaise01Setup,
      },
      {
        id: "raise",
        label: "对侧抬起",
        description: "一侧手臂与对侧腿小幅抬起，躯干不要旋转。",
        source: contralateralLimbRaise02Raise,
      },
    ],
  },
  DEAD_BUG: {
    primaryRef: "asset://exercise-guides/dead-bug-01-setup.jpg",
    stages: [
      {
        id: "setup",
        label: "准备",
        description: "仰卧抬起手脚，腰背保持稳定。",
        source: deadBug01Setup,
      },
      {
        id: "extend",
        label: "伸展",
        description: "对侧手臂和腿缓慢远离身体。",
        source: deadBug02Extend,
      },
      {
        id: "control",
        label: "控制",
        description: "继续伸展，同时保持腰背贴稳。",
        source: deadBug03Control,
      },
      {
        id: "finish",
        label: "到位",
        description: "在躯干不晃动的范围内停住。",
        source: deadBug04Finish,
      },
    ],
  },
  BIRD_DOG: {
    primaryRef: "asset://exercise-guides/bird-dog-01-setup.jpg",
    stages: [
      {
        id: "setup",
        label: "四点支撑",
        description: "双手双膝压稳，背部保持平直。",
        source: birdDog01Setup,
      },
      {
        id: "extend",
        label: "开始伸展",
        description: "对侧手脚缓慢离地。",
        source: birdDog02Extend,
      },
      {
        id: "control",
        label: "继续伸展",
        description: "髋部保持水平，避免身体旋转。",
        source: birdDog03Control,
      },
      {
        id: "finish",
        label: "伸直到位",
        description: "手脚延伸，躯干仍然稳定。",
        source: birdDog04Finish,
      },
    ],
  },
  PLANK: {
    primaryRef: "asset://exercise-guides/plank-01-setup.jpg",
    stages: [
      {
        id: "setup",
        label: "支撑定位",
        description: "前臂和脚尖压稳，身体接近直线。",
        source: plank01Setup,
      },
      {
        id: "hold",
        label: "稳定保持",
        description: "收紧腹部并自然呼吸，不塌腰。",
        source: plank02Hold,
      },
    ],
  },
  SMITH_FLAT_BENCH_PRESS: {
    primaryRef: "asset://exercise-guides/smith-flat-bench-press-01-setup.jpg",
    stages: [
      {
        id: "setup",
        label: "起始",
        description: "肩背和脚部先稳定支撑。",
        source: smithFlatBenchPress01Setup,
      },
      {
        id: "drive",
        label: "推起",
        description: "手腕稳定，沿可控路径推起负重。",
        source: smithFlatBenchPress02Drive,
      },
      {
        id: "finish",
        label: "完成",
        description: "手臂接近伸直，避免锁死关节。",
        source: smithFlatBenchPress03Finish,
      },
    ],
  },
  INCLINE_DUMBBELL_BENCH_PRESS_30: {
    primaryRef: "asset://exercise-guides/incline-dumbbell-bench-press-30-01-setup.jpg",
    stages: [
      {
        id: "setup",
        label: "起始",
        description: "肩背和脚部先稳定支撑。",
        source: inclineDumbbellBenchPress3001Setup,
      },
      {
        id: "drive",
        label: "推起",
        description: "手腕稳定，沿可控路径推起负重。",
        source: inclineDumbbellBenchPress3002Drive,
      },
      {
        id: "finish",
        label: "完成",
        description: "手臂接近伸直，避免锁死关节。",
        source: inclineDumbbellBenchPress3003Finish,
      },
    ],
  },
  SEATED_MACHINE_SHOULDER_PRESS: {
    primaryRef: "asset://exercise-guides/seated-machine-shoulder-press-01-setup.jpg",
    stages: [
      {
        id: "setup",
        label: "肩前",
        description: "核心收紧，负重稳定在肩部附近。",
        source: seatedMachineShoulderPress01Setup,
      },
      {
        id: "drive",
        label: "推举",
        description: "沿头部两侧向上推，避免腰部后仰。",
        source: seatedMachineShoulderPress02Drive,
      },
      {
        id: "finish",
        label: "顶端",
        description: "负重位于身体上方，肩颈保持放松。",
        source: seatedMachineShoulderPress03Finish,
      },
    ],
  },
  LEANING_PEC_DECK_FLY: {
    primaryRef: "asset://exercise-guides/leaning-pec-deck-fly-01-setup.jpg",
    stages: [
      {
        id: "setup",
        label: "胸前稳定",
        description: "肩背贴稳，手肘保持轻微弯曲。",
        source: leaningPecDeckFly01Setup,
      },
      {
        id: "drive",
        label: "向外展开",
        description: "沿弧线受控打开双臂，不让肩部过度后伸。",
        source: leaningPecDeckFly02Drive,
      },
      {
        id: "finish",
        label: "拉伸到位",
        description: "胸部有拉伸感时停住，再沿原路径夹回。",
        source: leaningPecDeckFly03Finish,
      },
    ],
  },
  MACHINE_SEATED_ROW: {
    primaryRef: "asset://exercise-guides/machine-seated-row-01-setup.jpg",
    stages: [
      {
        id: "setup",
        label: "伸臂",
        description: "躯干稳定，肩膀自然下沉。",
        source: machineSeatedRow01Setup,
      },
      {
        id: "drive",
        label: "后拉",
        description: "肘部向后，肩胛向中间收拢。",
        source: machineSeatedRow02Drive,
      },
      {
        id: "finish",
        label: "收紧",
        description: "握把靠近身体，避免大幅后仰。",
        source: machineSeatedRow03Finish,
      },
    ],
  },
  REVERSE_PEC_DECK_FLY: {
    primaryRef: "asset://exercise-guides/reverse-pec-deck-fly-01-setup.jpg",
    stages: [
      {
        id: "setup",
        label: "肩胛稳定",
        description: "站稳或俯身后先保持躯干稳定。",
        source: reversePecDeckFly01Setup,
      },
      {
        id: "drive",
        label: "向外展开",
        description: "肘部向外移动，肩部不要耸起。",
        source: reversePecDeckFly02Drive,
      },
      {
        id: "finish",
        label: "上背收紧",
        description: "肩部后侧和上背收紧后受控返回。",
        source: reversePecDeckFly03Finish,
      },
    ],
  },
  SMITH_SQUAT: {
    primaryRef: "asset://exercise-guides/smith-squat-01-setup.jpg",
    stages: [
      {
        id: "setup",
        label: "站稳",
        description: "脚掌稳定，负重靠近身体。",
        source: smithSquat01Setup,
      },
      {
        id: "drive",
        label: "下蹲",
        description: "屈髋屈膝，膝盖跟随脚尖方向。",
        source: smithSquat02Drive,
      },
      {
        id: "finish",
        label: "到位",
        description: "保持躯干稳定，在可控深度停住。",
        source: smithSquat03Finish,
      },
    ],
  },
  SEATED_LEG_PRESS: {
    primaryRef: "asset://exercise-guides/seated-leg-press-01-setup.jpg",
    stages: [
      {
        id: "setup",
        label: "屈膝准备",
        description: "背部和臀部贴稳靠垫，双脚踩实踏板。",
        source: seatedLegPress01Setup,
      },
      {
        id: "drive",
        label: "推开踏板",
        description: "膝盖跟随脚尖方向，脚跟持续发力。",
        source: seatedLegPress02Drive,
      },
      {
        id: "finish",
        label: "接近伸直",
        description: "腿部接近伸直时停住，不锁死膝盖。",
        source: seatedLegPress03Finish,
      },
    ],
  },
  DUMBBELL_REVERSE_LUNGE: {
    primaryRef: "asset://exercise-guides/dumbbell-reverse-lunge-01-setup.jpg",
    stages: [
      {
        id: "setup",
        label: "站稳",
        description: "躯干直立，双手稳定握住哑铃。",
        source: dumbbellReverseLunge01Setup,
      },
      {
        id: "drive",
        label: "向后迈步",
        description: "一脚受控后撤，前脚掌和脚跟保持稳定。",
        source: dumbbellReverseLunge02Drive,
      },
      {
        id: "finish",
        label: "下蹲到位",
        description: "前膝跟随脚尖，后膝接近地面后停住。",
        source: dumbbellReverseLunge03Finish,
      },
    ],
  },
  SEATED_LEG_EXTENSION: {
    primaryRef: "asset://exercise-guides/seated-leg-extension-01-setup.jpg",
    stages: [
      {
        id: "setup",
        label: "屈膝坐稳",
        description: "膝盖对齐器械转轴，滚垫贴在小腿前侧。",
        source: seatedLegExtension01Setup,
      },
      {
        id: "drive",
        label: "伸直膝盖",
        description: "保持臀部贴稳，平稳抬起小腿。",
        source: seatedLegExtension02Drive,
      },
      {
        id: "finish",
        label: "顶端收紧",
        description: "接近伸直时停顿，不用惯性锁死膝盖。",
        source: seatedLegExtension03Finish,
      },
    ],
  },
  MACHINE_CRUNCH: {
    primaryRef: "asset://exercise-guides/machine-crunch-01-setup.jpg",
    stages: [
      {
        id: "setup",
        label: "坐稳",
        description: "髋部和双脚固定，胸廓保持自然。",
        source: machineCrunch01Setup,
      },
      {
        id: "drive",
        label: "卷曲躯干",
        description: "肋骨向骨盆靠近，用腹部带动器械。",
        source: machineCrunch02Drive,
      },
      {
        id: "finish",
        label: "腹部收紧",
        description: "在髋部不抬起的范围内停住，再受控返回。",
        source: machineCrunch03Finish,
      },
    ],
  },
  INCLINE_DUMBBELL_FLY: {
    primaryRef: "asset://exercise-guides/incline-dumbbell-fly-01-setup.jpg",
    stages: [
      {
        id: "setup",
        label: "胸前稳定",
        description: "肩背贴稳，手肘保持轻微弯曲。",
        source: inclineDumbbellFly01Setup,
      },
      {
        id: "drive",
        label: "向外展开",
        description: "沿弧线受控打开双臂，不让肩部过度后伸。",
        source: inclineDumbbellFly02Drive,
      },
      {
        id: "finish",
        label: "拉伸到位",
        description: "胸部有拉伸感时停住，再沿原路径夹回。",
        source: inclineDumbbellFly03Finish,
      },
    ],
  },
  MACHINE_HIP_THRUST: {
    primaryRef: "asset://exercise-guides/machine-hip-thrust-01-setup.jpg",
    stages: [
      {
        id: "setup",
        label: "落髋准备",
        description: "上背和双脚稳定，髋部受垫带固定。",
        source: machineHipThrust01Setup,
      },
      {
        id: "drive",
        label: "抬起髋部",
        description: "脚跟发力，让臀部带动髋部上升。",
        source: machineHipThrust02Drive,
      },
      {
        id: "finish",
        label: "顶部收紧",
        description: "臀部夹紧并停顿，肋骨下沉不过度挺腰。",
        source: machineHipThrust03Finish,
      },
    ],
  },
  MACHINE_LEG_CURL: {
    primaryRef: "asset://exercise-guides/machine-leg-curl-01-setup.jpg",
    stages: [
      {
        id: "setup",
        label: "伸腿准备",
        description: "俯卧贴稳，膝盖对齐转轴，滚垫位于脚跟上方。",
        source: machineLegCurl01Setup,
      },
      {
        id: "drive",
        label: "屈膝弯腿",
        description: "保持髋部贴垫，让脚跟平稳靠近臀部。",
        source: machineLegCurl02Drive,
      },
      {
        id: "finish",
        label: "收缩到位",
        description: "大腿后侧收紧后停顿，再缓慢放回。",
        source: machineLegCurl03Finish,
      },
    ],
  },
  MACHINE_HIP_ABDUCTION: {
    primaryRef: "asset://exercise-guides/machine-hip-abduction-01-setup.jpg",
    stages: [
      {
        id: "setup",
        label: "并腿坐稳",
        description: "背部贴稳，器械垫贴住大腿外侧。",
        source: machineHipAbduction01Setup,
      },
      {
        id: "drive",
        label: "向外打开",
        description: "从髋部推动双膝向外，躯干保持稳定。",
        source: machineHipAbduction02Drive,
      },
      {
        id: "finish",
        label: "外侧收紧",
        description: "在可控幅度停顿，再缓慢合回。",
        source: machineHipAbduction03Finish,
      },
    ],
  },
  STANDING_CALF_RAISE: {
    primaryRef: "asset://exercise-guides/standing-calf-raise-01-setup.jpg",
    stages: [
      {
        id: "setup",
        label: "脚跟落地",
        description: "双手轻扶墙面，双脚平行站稳。",
        source: standingCalfRaise01Setup,
      },
      {
        id: "drive",
        label: "提起脚跟",
        description: "缓慢抬起脚跟，把重心保持在前脚掌。",
        source: standingCalfRaise02Drive,
      },
      {
        id: "finish",
        label: "稳定顶端",
        description: "身体保持直立，再缓慢放下脚跟。",
        source: standingCalfRaise03Finish,
      },
    ],
  },
} as const

export const staticSourcesByAssetRef = {
  "asset://exercise-guides/goblet-squat-01-setup.jpg": gobletSquat01Setup,
  "asset://exercise-guides/goblet-squat-02-drive.jpg": gobletSquat02Drive,
  "asset://exercise-guides/goblet-squat-03-finish.jpg": gobletSquat03Finish,
  "asset://exercise-guides/dumbbell-front-squat-01-setup.jpg": dumbbellFrontSquat01Setup,
  "asset://exercise-guides/dumbbell-front-squat-02-drive.jpg": dumbbellFrontSquat02Drive,
  "asset://exercise-guides/dumbbell-front-squat-03-finish.jpg": dumbbellFrontSquat03Finish,
  "asset://exercise-guides/bodyweight-squat-01-setup.jpg": bodyweightSquat01Setup,
  "asset://exercise-guides/bodyweight-squat-02-drive.jpg": bodyweightSquat02Drive,
  "asset://exercise-guides/bodyweight-squat-03-finish.jpg": bodyweightSquat03Finish,
  "asset://exercise-guides/prisoner-squat-01-setup.jpg": prisonerSquat01Setup,
  "asset://exercise-guides/prisoner-squat-02-drive.jpg": prisonerSquat02Drive,
  "asset://exercise-guides/prisoner-squat-03-finish.jpg": prisonerSquat03Finish,
  "asset://exercise-guides/standing-wall-calf-raise-01-setup.jpg": standingWallCalfRaise01Setup,
  "asset://exercise-guides/standing-wall-calf-raise-02-drive.jpg": standingWallCalfRaise02Drive,
  "asset://exercise-guides/standing-wall-calf-raise-03-finish.jpg": standingWallCalfRaise03Finish,
  "asset://exercise-guides/dumbbell-romanian-deadlift-01-setup.jpg": dumbbellRomanianDeadlift01Setup,
  "asset://exercise-guides/dumbbell-romanian-deadlift-02-drive.jpg": dumbbellRomanianDeadlift02Drive,
  "asset://exercise-guides/dumbbell-romanian-deadlift-03-finish.jpg": dumbbellRomanianDeadlift03Finish,
  "asset://exercise-guides/dumbbell-deadlift-01-setup.jpg": dumbbellDeadlift01Setup,
  "asset://exercise-guides/dumbbell-deadlift-02-drive.jpg": dumbbellDeadlift02Drive,
  "asset://exercise-guides/dumbbell-deadlift-03-finish.jpg": dumbbellDeadlift03Finish,
  "asset://exercise-guides/bodyweight-hip-hinge-01-setup.jpg": bodyweightHipHinge01Setup,
  "asset://exercise-guides/bodyweight-hip-hinge-02-drive.jpg": bodyweightHipHinge02Drive,
  "asset://exercise-guides/bodyweight-hip-hinge-03-finish.jpg": bodyweightHipHinge03Finish,
  "asset://exercise-guides/glute-bridge-exercise-01-setup.jpg": gluteBridgeExercise01Setup,
  "asset://exercise-guides/glute-bridge-exercise-02-lift.jpg": gluteBridgeExercise02Lift,
  "asset://exercise-guides/dumbbell-bench-press-01-setup.jpg": dumbbellBenchPress01Setup,
  "asset://exercise-guides/dumbbell-bench-press-02-drive.jpg": dumbbellBenchPress02Drive,
  "asset://exercise-guides/dumbbell-bench-press-03-finish.jpg": dumbbellBenchPress03Finish,
  "asset://exercise-guides/dumbbell-floor-press-01-setup.jpg": dumbbellFloorPress01Setup,
  "asset://exercise-guides/dumbbell-floor-press-02-drive.jpg": dumbbellFloorPress02Drive,
  "asset://exercise-guides/dumbbell-floor-press-03-finish.jpg": dumbbellFloorPress03Finish,
  "asset://exercise-guides/incline-push-up-01-setup.jpg": inclinePushUp01Setup,
  "asset://exercise-guides/incline-push-up-02-drive.jpg": inclinePushUp02Drive,
  "asset://exercise-guides/incline-push-up-03-finish.jpg": inclinePushUp03Finish,
  "asset://exercise-guides/bent-knee-push-up-01-setup.jpg": bentKneePushUp01Setup,
  "asset://exercise-guides/bent-knee-push-up-02-lower.jpg": bentKneePushUp02Lower,
  "asset://exercise-guides/push-up-01-setup.jpg": pushUp01Setup,
  "asset://exercise-guides/push-up-02-drive.jpg": pushUp02Drive,
  "asset://exercise-guides/push-up-03-finish.jpg": pushUp03Finish,
  "asset://exercise-guides/wall-push-up-01-setup.jpg": wallPushUp01Setup,
  "asset://exercise-guides/wall-push-up-02-drive.jpg": wallPushUp02Drive,
  "asset://exercise-guides/wall-push-up-03-finish.jpg": wallPushUp03Finish,
  "asset://exercise-guides/seated-cable-row-01-setup.jpg": seatedCableRow01Setup,
  "asset://exercise-guides/seated-cable-row-02-drive.jpg": seatedCableRow02Drive,
  "asset://exercise-guides/seated-cable-row-03-finish.jpg": seatedCableRow03Finish,
  "asset://exercise-guides/cable-high-row-01-setup.jpg": cableHighRow01Setup,
  "asset://exercise-guides/cable-high-row-02-drive.jpg": cableHighRow02Drive,
  "asset://exercise-guides/cable-high-row-03-finish.jpg": cableHighRow03Finish,
  "asset://exercise-guides/cable-single-arm-row-01-setup.jpg": cableSingleArmRow01Setup,
  "asset://exercise-guides/cable-single-arm-row-02-drive.jpg": cableSingleArmRow02Drive,
  "asset://exercise-guides/cable-single-arm-row-03-finish.jpg": cableSingleArmRow03Finish,
  "asset://exercise-guides/one-arm-dumbbell-row-01-setup.jpg": oneArmDumbbellRow01Setup,
  "asset://exercise-guides/one-arm-dumbbell-row-02-drive.jpg": oneArmDumbbellRow02Drive,
  "asset://exercise-guides/one-arm-dumbbell-row-03-finish.jpg": oneArmDumbbellRow03Finish,
  "asset://exercise-guides/dumbbell-overhead-press-01-setup.jpg": dumbbellOverheadPress01Setup,
  "asset://exercise-guides/dumbbell-overhead-press-02-drive.jpg": dumbbellOverheadPress02Drive,
  "asset://exercise-guides/dumbbell-overhead-press-03-finish.jpg": dumbbellOverheadPress03Finish,
  "asset://exercise-guides/seated-dumbbell-press-01-setup.jpg": seatedDumbbellPress01Setup,
  "asset://exercise-guides/seated-dumbbell-press-02-drive.jpg": seatedDumbbellPress02Drive,
  "asset://exercise-guides/seated-dumbbell-press-03-finish.jpg": seatedDumbbellPress03Finish,
  "asset://exercise-guides/single-arm-dumbbell-press-01-setup.jpg": singleArmDumbbellPress01Setup,
  "asset://exercise-guides/single-arm-dumbbell-press-02-drive.jpg": singleArmDumbbellPress02Drive,
  "asset://exercise-guides/single-arm-dumbbell-press-03-finish.jpg": singleArmDumbbellPress03Finish,
  "asset://exercise-guides/dumbbell-lateral-raise-01-setup.jpg": dumbbellLateralRaise01Setup,
  "asset://exercise-guides/dumbbell-lateral-raise-02-drive.jpg": dumbbellLateralRaise02Drive,
  "asset://exercise-guides/dumbbell-lateral-raise-03-finish.jpg": dumbbellLateralRaise03Finish,
  "asset://exercise-guides/single-arm-dumbbell-lateral-raise-01-setup.jpg": singleArmDumbbellLateralRaise01Setup,
  "asset://exercise-guides/single-arm-dumbbell-lateral-raise-02-drive.jpg": singleArmDumbbellLateralRaise02Drive,
  "asset://exercise-guides/single-arm-dumbbell-lateral-raise-03-finish.jpg": singleArmDumbbellLateralRaise03Finish,
  "asset://exercise-guides/cable-lateral-raise-01-setup.jpg": cableLateralRaise01Setup,
  "asset://exercise-guides/cable-lateral-raise-02-drive.jpg": cableLateralRaise02Drive,
  "asset://exercise-guides/cable-lateral-raise-03-finish.jpg": cableLateralRaise03Finish,
  "asset://exercise-guides/dumbbell-biceps-curl-01-setup.jpg": dumbbellBicepsCurl01Setup,
  "asset://exercise-guides/dumbbell-biceps-curl-02-drive.jpg": dumbbellBicepsCurl02Drive,
  "asset://exercise-guides/dumbbell-biceps-curl-03-finish.jpg": dumbbellBicepsCurl03Finish,
  "asset://exercise-guides/dumbbell-hammer-curl-01-setup.jpg": dumbbellHammerCurl01Setup,
  "asset://exercise-guides/dumbbell-hammer-curl-02-drive.jpg": dumbbellHammerCurl02Drive,
  "asset://exercise-guides/dumbbell-hammer-curl-03-finish.jpg": dumbbellHammerCurl03Finish,
  "asset://exercise-guides/cable-biceps-curl-01-setup.jpg": cableBicepsCurl01Setup,
  "asset://exercise-guides/cable-biceps-curl-02-drive.jpg": cableBicepsCurl02Drive,
  "asset://exercise-guides/cable-biceps-curl-03-finish.jpg": cableBicepsCurl03Finish,
  "asset://exercise-guides/cable-triceps-pushdown-01-setup.jpg": cableTricepsPushdown01Setup,
  "asset://exercise-guides/cable-triceps-pushdown-02-drive.jpg": cableTricepsPushdown02Drive,
  "asset://exercise-guides/cable-triceps-pushdown-03-finish.jpg": cableTricepsPushdown03Finish,
  "asset://exercise-guides/dumbbell-overhead-triceps-extension-01-setup.jpg": dumbbellOverheadTricepsExtension01Setup,
  "asset://exercise-guides/dumbbell-overhead-triceps-extension-02-drive.jpg": dumbbellOverheadTricepsExtension02Drive,
  "asset://exercise-guides/dumbbell-overhead-triceps-extension-03-finish.jpg": dumbbellOverheadTricepsExtension03Finish,
  "asset://exercise-guides/dumbbell-lying-triceps-extension-01-setup.jpg": dumbbellLyingTricepsExtension01Setup,
  "asset://exercise-guides/dumbbell-lying-triceps-extension-02-drive.jpg": dumbbellLyingTricepsExtension02Drive,
  "asset://exercise-guides/dumbbell-lying-triceps-extension-03-finish.jpg": dumbbellLyingTricepsExtension03Finish,
  "asset://exercise-guides/dumbbell-reverse-fly-01-setup.jpg": dumbbellReverseFly01Setup,
  "asset://exercise-guides/dumbbell-reverse-fly-02-drive.jpg": dumbbellReverseFly02Drive,
  "asset://exercise-guides/dumbbell-reverse-fly-03-finish.jpg": dumbbellReverseFly03Finish,
  "asset://exercise-guides/cable-reverse-fly-01-setup.jpg": cableReverseFly01Setup,
  "asset://exercise-guides/cable-reverse-fly-02-drive.jpg": cableReverseFly02Drive,
  "asset://exercise-guides/cable-reverse-fly-03-finish.jpg": cableReverseFly03Finish,
  "asset://exercise-guides/cable-face-pull-01-setup.jpg": cableFacePull01Setup,
  "asset://exercise-guides/cable-face-pull-02-drive.jpg": cableFacePull02Drive,
  "asset://exercise-guides/cable-face-pull-03-finish.jpg": cableFacePull03Finish,
  "asset://exercise-guides/dumbbell-shrug-01-setup.jpg": dumbbellShrug01Setup,
  "asset://exercise-guides/dumbbell-shrug-02-drive.jpg": dumbbellShrug02Drive,
  "asset://exercise-guides/dumbbell-shrug-03-finish.jpg": dumbbellShrug03Finish,
  "asset://exercise-guides/cable-shrug-01-setup.jpg": cableShrug01Setup,
  "asset://exercise-guides/cable-shrug-02-drive.jpg": cableShrug02Drive,
  "asset://exercise-guides/cable-shrug-03-finish.jpg": cableShrug03Finish,
  "asset://exercise-guides/machine-shrug-01-setup.jpg": machineShrug01Setup,
  "asset://exercise-guides/machine-shrug-02-drive.jpg": machineShrug02Drive,
  "asset://exercise-guides/machine-shrug-03-finish.jpg": machineShrug03Finish,
  "asset://exercise-guides/lat-pulldown-01-setup.jpg": latPulldown01Setup,
  "asset://exercise-guides/lat-pulldown-02-drive.jpg": latPulldown02Drive,
  "asset://exercise-guides/lat-pulldown-03-finish.jpg": latPulldown03Finish,
  "asset://exercise-guides/cable-straight-arm-pulldown-01-setup.jpg": cableStraightArmPulldown01Setup,
  "asset://exercise-guides/cable-straight-arm-pulldown-02-drive.jpg": cableStraightArmPulldown02Drive,
  "asset://exercise-guides/cable-straight-arm-pulldown-03-finish.jpg": cableStraightArmPulldown03Finish,
  "asset://exercise-guides/neutral-grip-pulldown-01-setup.jpg": neutralGripPulldown01Setup,
  "asset://exercise-guides/neutral-grip-pulldown-02-drive.jpg": neutralGripPulldown02Drive,
  "asset://exercise-guides/neutral-grip-pulldown-03-finish.jpg": neutralGripPulldown03Finish,
  "asset://exercise-guides/prone-w-raise-01-setup.jpg": proneWRaise01Setup,
  "asset://exercise-guides/prone-w-raise-02-drive.jpg": proneWRaise02Drive,
  "asset://exercise-guides/prone-w-raise-03-finish.jpg": proneWRaise03Finish,
  "asset://exercise-guides/prone-y-raise-01-setup.jpg": proneYRaise01Setup,
  "asset://exercise-guides/prone-y-raise-02-drive.jpg": proneYRaise02Drive,
  "asset://exercise-guides/prone-y-raise-03-finish.jpg": proneYRaise03Finish,
  "asset://exercise-guides/floor-prone-cobra-01-setup.jpg": floorProneCobra01Setup,
  "asset://exercise-guides/floor-prone-cobra-02-lift.jpg": floorProneCobra02Lift,
  "asset://exercise-guides/contralateral-limb-raise-01-setup.jpg": contralateralLimbRaise01Setup,
  "asset://exercise-guides/contralateral-limb-raise-02-raise.jpg": contralateralLimbRaise02Raise,
  "asset://exercise-guides/dead-bug-01-setup.jpg": deadBug01Setup,
  "asset://exercise-guides/dead-bug-02-extend.jpg": deadBug02Extend,
  "asset://exercise-guides/dead-bug-03-control.jpg": deadBug03Control,
  "asset://exercise-guides/dead-bug-04-finish.jpg": deadBug04Finish,
  "asset://exercise-guides/bird-dog-01-setup.jpg": birdDog01Setup,
  "asset://exercise-guides/bird-dog-02-extend.jpg": birdDog02Extend,
  "asset://exercise-guides/bird-dog-03-control.jpg": birdDog03Control,
  "asset://exercise-guides/bird-dog-04-finish.jpg": birdDog04Finish,
  "asset://exercise-guides/plank-01-setup.jpg": plank01Setup,
  "asset://exercise-guides/plank-02-hold.jpg": plank02Hold,
  "asset://exercise-guides/smith-flat-bench-press-01-setup.jpg": smithFlatBenchPress01Setup,
  "asset://exercise-guides/smith-flat-bench-press-02-drive.jpg": smithFlatBenchPress02Drive,
  "asset://exercise-guides/smith-flat-bench-press-03-finish.jpg": smithFlatBenchPress03Finish,
  "asset://exercise-guides/incline-dumbbell-bench-press-30-01-setup.jpg": inclineDumbbellBenchPress3001Setup,
  "asset://exercise-guides/incline-dumbbell-bench-press-30-02-drive.jpg": inclineDumbbellBenchPress3002Drive,
  "asset://exercise-guides/incline-dumbbell-bench-press-30-03-finish.jpg": inclineDumbbellBenchPress3003Finish,
  "asset://exercise-guides/seated-machine-shoulder-press-01-setup.jpg": seatedMachineShoulderPress01Setup,
  "asset://exercise-guides/seated-machine-shoulder-press-02-drive.jpg": seatedMachineShoulderPress02Drive,
  "asset://exercise-guides/seated-machine-shoulder-press-03-finish.jpg": seatedMachineShoulderPress03Finish,
  "asset://exercise-guides/leaning-pec-deck-fly-01-setup.jpg": leaningPecDeckFly01Setup,
  "asset://exercise-guides/leaning-pec-deck-fly-02-drive.jpg": leaningPecDeckFly02Drive,
  "asset://exercise-guides/leaning-pec-deck-fly-03-finish.jpg": leaningPecDeckFly03Finish,
  "asset://exercise-guides/machine-seated-row-01-setup.jpg": machineSeatedRow01Setup,
  "asset://exercise-guides/machine-seated-row-02-drive.jpg": machineSeatedRow02Drive,
  "asset://exercise-guides/machine-seated-row-03-finish.jpg": machineSeatedRow03Finish,
  "asset://exercise-guides/reverse-pec-deck-fly-01-setup.jpg": reversePecDeckFly01Setup,
  "asset://exercise-guides/reverse-pec-deck-fly-02-drive.jpg": reversePecDeckFly02Drive,
  "asset://exercise-guides/reverse-pec-deck-fly-03-finish.jpg": reversePecDeckFly03Finish,
  "asset://exercise-guides/smith-squat-01-setup.jpg": smithSquat01Setup,
  "asset://exercise-guides/smith-squat-02-drive.jpg": smithSquat02Drive,
  "asset://exercise-guides/smith-squat-03-finish.jpg": smithSquat03Finish,
  "asset://exercise-guides/seated-leg-press-01-setup.jpg": seatedLegPress01Setup,
  "asset://exercise-guides/seated-leg-press-02-drive.jpg": seatedLegPress02Drive,
  "asset://exercise-guides/seated-leg-press-03-finish.jpg": seatedLegPress03Finish,
  "asset://exercise-guides/dumbbell-reverse-lunge-01-setup.jpg": dumbbellReverseLunge01Setup,
  "asset://exercise-guides/dumbbell-reverse-lunge-02-drive.jpg": dumbbellReverseLunge02Drive,
  "asset://exercise-guides/dumbbell-reverse-lunge-03-finish.jpg": dumbbellReverseLunge03Finish,
  "asset://exercise-guides/seated-leg-extension-01-setup.jpg": seatedLegExtension01Setup,
  "asset://exercise-guides/seated-leg-extension-02-drive.jpg": seatedLegExtension02Drive,
  "asset://exercise-guides/seated-leg-extension-03-finish.jpg": seatedLegExtension03Finish,
  "asset://exercise-guides/machine-crunch-01-setup.jpg": machineCrunch01Setup,
  "asset://exercise-guides/machine-crunch-02-drive.jpg": machineCrunch02Drive,
  "asset://exercise-guides/machine-crunch-03-finish.jpg": machineCrunch03Finish,
  "asset://exercise-guides/incline-dumbbell-fly-01-setup.jpg": inclineDumbbellFly01Setup,
  "asset://exercise-guides/incline-dumbbell-fly-02-drive.jpg": inclineDumbbellFly02Drive,
  "asset://exercise-guides/incline-dumbbell-fly-03-finish.jpg": inclineDumbbellFly03Finish,
  "asset://exercise-guides/machine-hip-thrust-01-setup.jpg": machineHipThrust01Setup,
  "asset://exercise-guides/machine-hip-thrust-02-drive.jpg": machineHipThrust02Drive,
  "asset://exercise-guides/machine-hip-thrust-03-finish.jpg": machineHipThrust03Finish,
  "asset://exercise-guides/machine-leg-curl-01-setup.jpg": machineLegCurl01Setup,
  "asset://exercise-guides/machine-leg-curl-02-drive.jpg": machineLegCurl02Drive,
  "asset://exercise-guides/machine-leg-curl-03-finish.jpg": machineLegCurl03Finish,
  "asset://exercise-guides/machine-hip-abduction-01-setup.jpg": machineHipAbduction01Setup,
  "asset://exercise-guides/machine-hip-abduction-02-drive.jpg": machineHipAbduction02Drive,
  "asset://exercise-guides/machine-hip-abduction-03-finish.jpg": machineHipAbduction03Finish,
  "asset://exercise-guides/standing-calf-raise-01-setup.jpg": standingCalfRaise01Setup,
  "asset://exercise-guides/standing-calf-raise-02-drive.jpg": standingCalfRaise02Drive,
  "asset://exercise-guides/standing-calf-raise-03-finish.jpg": standingCalfRaise03Finish,
} as const
