/* Generated by scripts/build_static_exercise_guides.py. Do not edit manually. */
import gobletSquat01Setup from './goblet-squat-01-setup.jpg'
import gobletSquat02Drive from './goblet-squat-02-drive.jpg'
import gobletSquat03Finish from './goblet-squat-03-finish.jpg'
import dumbbellFrontSquat01Setup from './dumbbell-front-squat-01-setup.jpg'
import dumbbellFrontSquat02Drive from './dumbbell-front-squat-02-drive.jpg'
import dumbbellFrontSquat03Finish from './dumbbell-front-squat-03-finish.jpg'
import bodyweightSquat01Setup from './bodyweight-squat-01-setup.jpg'
import bodyweightSquat02Drive from './bodyweight-squat-02-drive.jpg'
import bodyweightSquat03Finish from './bodyweight-squat-03-finish.jpg'
import dumbbellRomanianDeadlift01Setup from './dumbbell-romanian-deadlift-01-setup.jpg'
import dumbbellRomanianDeadlift02Drive from './dumbbell-romanian-deadlift-02-drive.jpg'
import dumbbellRomanianDeadlift03Finish from './dumbbell-romanian-deadlift-03-finish.jpg'
import dumbbellDeadlift01Setup from './dumbbell-deadlift-01-setup.jpg'
import dumbbellDeadlift02Drive from './dumbbell-deadlift-02-drive.jpg'
import dumbbellDeadlift03Finish from './dumbbell-deadlift-03-finish.jpg'
import bodyweightHipHinge01Setup from './bodyweight-hip-hinge-01-setup.jpg'
import bodyweightHipHinge02Drive from './bodyweight-hip-hinge-02-drive.jpg'
import bodyweightHipHinge03Finish from './bodyweight-hip-hinge-03-finish.jpg'
import dumbbellBenchPress01Setup from './dumbbell-bench-press-01-setup.jpg'
import dumbbellBenchPress02Drive from './dumbbell-bench-press-02-drive.jpg'
import dumbbellBenchPress03Finish from './dumbbell-bench-press-03-finish.jpg'
import dumbbellFloorPress01Setup from './dumbbell-floor-press-01-setup.jpg'
import dumbbellFloorPress02Drive from './dumbbell-floor-press-02-drive.jpg'
import dumbbellFloorPress03Finish from './dumbbell-floor-press-03-finish.jpg'
import inclinePushUp01Setup from './incline-push-up-01-setup.jpg'
import inclinePushUp02Drive from './incline-push-up-02-drive.jpg'
import inclinePushUp03Finish from './incline-push-up-03-finish.jpg'
import seatedCableRow01Setup from './seated-cable-row-01-setup.jpg'
import seatedCableRow02Drive from './seated-cable-row-02-drive.jpg'
import seatedCableRow03Finish from './seated-cable-row-03-finish.jpg'
import cableHighRow01Setup from './cable-high-row-01-setup.jpg'
import cableHighRow02Drive from './cable-high-row-02-drive.jpg'
import cableHighRow03Finish from './cable-high-row-03-finish.jpg'
import cableSingleArmRow01Setup from './cable-single-arm-row-01-setup.jpg'
import cableSingleArmRow02Drive from './cable-single-arm-row-02-drive.jpg'
import cableSingleArmRow03Finish from './cable-single-arm-row-03-finish.jpg'
import dumbbellOverheadPress01Setup from './dumbbell-overhead-press-01-setup.jpg'
import dumbbellOverheadPress02Drive from './dumbbell-overhead-press-02-drive.jpg'
import dumbbellOverheadPress03Finish from './dumbbell-overhead-press-03-finish.jpg'
import seatedDumbbellPress01Setup from './seated-dumbbell-press-01-setup.jpg'
import seatedDumbbellPress02Drive from './seated-dumbbell-press-02-drive.jpg'
import seatedDumbbellPress03Finish from './seated-dumbbell-press-03-finish.jpg'
import singleArmDumbbellPress01Setup from './single-arm-dumbbell-press-01-setup.jpg'
import singleArmDumbbellPress02Drive from './single-arm-dumbbell-press-02-drive.jpg'
import singleArmDumbbellPress03Finish from './single-arm-dumbbell-press-03-finish.jpg'
import latPulldown01Setup from './lat-pulldown-01-setup.jpg'
import latPulldown02Drive from './lat-pulldown-02-drive.jpg'
import latPulldown03Finish from './lat-pulldown-03-finish.jpg'
import cableStraightArmPulldown01Setup from './cable-straight-arm-pulldown-01-setup.jpg'
import cableStraightArmPulldown02Drive from './cable-straight-arm-pulldown-02-drive.jpg'
import cableStraightArmPulldown03Finish from './cable-straight-arm-pulldown-03-finish.jpg'
import neutralGripPulldown01Setup from './neutral-grip-pulldown-01-setup.jpg'
import neutralGripPulldown02Drive from './neutral-grip-pulldown-02-drive.jpg'
import neutralGripPulldown03Finish from './neutral-grip-pulldown-03-finish.jpg'
import proneWRaise01Setup from './prone-w-raise-01-setup.jpg'
import proneWRaise02Drive from './prone-w-raise-02-drive.jpg'
import proneWRaise03Finish from './prone-w-raise-03-finish.jpg'
import proneYRaise01Setup from './prone-y-raise-01-setup.jpg'
import proneYRaise02Drive from './prone-y-raise-02-drive.jpg'
import proneYRaise03Finish from './prone-y-raise-03-finish.jpg'
import deadBug01Setup from './dead-bug-01-setup.jpg'
import deadBug02Extend from './dead-bug-02-extend.jpg'
import deadBug03Control from './dead-bug-03-control.jpg'
import deadBug04Finish from './dead-bug-04-finish.jpg'
import birdDog01Setup from './bird-dog-01-setup.jpg'
import birdDog02Extend from './bird-dog-02-extend.jpg'
import birdDog03Control from './bird-dog-03-control.jpg'
import birdDog04Finish from './bird-dog-04-finish.jpg'
import plank01Setup from './plank-01-setup.jpg'
import plank02Hold from './plank-02-hold.jpg'

export const staticGuidesByExerciseCode = {
  GOBLET_SQUAT: {
    primaryRef: "asset://exercise-guides/goblet-squat-01-setup.jpg",
    stages: [
      {
        id: "setup",
        label: "站稳",
        description: "脚掌稳定，负重靠近身体。",
        source: gobletSquat01Setup,
      },
      {
        id: "drive",
        label: "下蹲",
        description: "屈髋屈膝，膝盖跟随脚尖方向。",
        source: gobletSquat02Drive,
      },
      {
        id: "finish",
        label: "到位",
        description: "保持躯干稳定，在可控深度停住。",
        source: gobletSquat03Finish,
      },
    ],
  },
  DUMBBELL_FRONT_SQUAT: {
    primaryRef: "asset://exercise-guides/dumbbell-front-squat-01-setup.jpg",
    stages: [
      {
        id: "setup",
        label: "站稳",
        description: "脚掌稳定，负重靠近身体。",
        source: dumbbellFrontSquat01Setup,
      },
      {
        id: "drive",
        label: "下蹲",
        description: "屈髋屈膝，膝盖跟随脚尖方向。",
        source: dumbbellFrontSquat02Drive,
      },
      {
        id: "finish",
        label: "到位",
        description: "保持躯干稳定，在可控深度停住。",
        source: dumbbellFrontSquat03Finish,
      },
    ],
  },
  BODYWEIGHT_SQUAT: {
    primaryRef: "asset://exercise-guides/bodyweight-squat-01-setup.jpg",
    stages: [
      {
        id: "setup",
        label: "站稳",
        description: "脚掌稳定，负重靠近身体。",
        source: bodyweightSquat01Setup,
      },
      {
        id: "drive",
        label: "下蹲",
        description: "屈髋屈膝，膝盖跟随脚尖方向。",
        source: bodyweightSquat02Drive,
      },
      {
        id: "finish",
        label: "到位",
        description: "保持躯干稳定，在可控深度停住。",
        source: bodyweightSquat03Finish,
      },
    ],
  },
  DUMBBELL_ROMANIAN_DEADLIFT: {
    primaryRef: "asset://exercise-guides/dumbbell-romanian-deadlift-01-setup.jpg",
    stages: [
      {
        id: "setup",
        label: "站稳",
        description: "脚掌压稳，背部保持自然。",
        source: dumbbellRomanianDeadlift01Setup,
      },
      {
        id: "drive",
        label: "送髋",
        description: "髋部向后，负重贴近腿部。",
        source: dumbbellRomanianDeadlift02Drive,
      },
      {
        id: "finish",
        label: "到位",
        description: "大腿后侧有拉伸感时保持稳定。",
        source: dumbbellRomanianDeadlift03Finish,
      },
    ],
  },
  DUMBBELL_DEADLIFT: {
    primaryRef: "asset://exercise-guides/dumbbell-deadlift-01-setup.jpg",
    stages: [
      {
        id: "setup",
        label: "握稳",
        description: "哑铃靠近小腿，脚掌压稳并保持背部自然。",
        source: dumbbellDeadlift01Setup,
      },
      {
        id: "drive",
        label: "提起",
        description: "脚掌发力站起，负重持续贴近腿部。",
        source: dumbbellDeadlift02Drive,
      },
      {
        id: "finish",
        label: "站直",
        description: "髋膝伸直后稳定站立，避免身体后仰。",
        source: dumbbellDeadlift03Finish,
      },
    ],
  },
  BODYWEIGHT_HIP_HINGE: {
    primaryRef: "asset://exercise-guides/bodyweight-hip-hinge-01-setup.jpg",
    stages: [
      {
        id: "setup",
        label: "站稳",
        description: "脚掌压稳，背部保持自然。",
        source: bodyweightHipHinge01Setup,
      },
      {
        id: "drive",
        label: "送髋",
        description: "髋部向后，负重贴近腿部。",
        source: bodyweightHipHinge02Drive,
      },
      {
        id: "finish",
        label: "到位",
        description: "大腿后侧有拉伸感时保持稳定。",
        source: bodyweightHipHinge03Finish,
      },
    ],
  },
  DUMBBELL_BENCH_PRESS: {
    primaryRef: "asset://exercise-guides/dumbbell-bench-press-01-setup.jpg",
    stages: [
      {
        id: "setup",
        label: "起始",
        description: "肩背和脚部先稳定支撑。",
        source: dumbbellBenchPress01Setup,
      },
      {
        id: "drive",
        label: "推起",
        description: "手腕稳定，沿可控路径推起负重。",
        source: dumbbellBenchPress02Drive,
      },
      {
        id: "finish",
        label: "完成",
        description: "手臂接近伸直，避免锁死关节。",
        source: dumbbellBenchPress03Finish,
      },
    ],
  },
  DUMBBELL_FLOOR_PRESS: {
    primaryRef: "asset://exercise-guides/dumbbell-floor-press-01-setup.jpg",
    stages: [
      {
        id: "setup",
        label: "起始",
        description: "肩背和脚部先稳定支撑。",
        source: dumbbellFloorPress01Setup,
      },
      {
        id: "drive",
        label: "推起",
        description: "手腕稳定，沿可控路径推起负重。",
        source: dumbbellFloorPress02Drive,
      },
      {
        id: "finish",
        label: "完成",
        description: "手臂接近伸直，避免锁死关节。",
        source: dumbbellFloorPress03Finish,
      },
    ],
  },
  INCLINE_PUSH_UP: {
    primaryRef: "asset://exercise-guides/incline-push-up-01-setup.jpg",
    stages: [
      {
        id: "setup",
        label: "支撑",
        description: "双手撑稳，身体保持一条直线。",
        source: inclinePushUp01Setup,
      },
      {
        id: "drive",
        label: "下降",
        description: "屈肘让胸口靠近支撑面。",
        source: inclinePushUp02Drive,
      },
      {
        id: "finish",
        label: "最低点",
        description: "核心收紧，不塌腰或耸肩。",
        source: inclinePushUp03Finish,
      },
    ],
  },
  SEATED_CABLE_ROW: {
    primaryRef: "asset://exercise-guides/seated-cable-row-01-setup.jpg",
    stages: [
      {
        id: "setup",
        label: "伸臂",
        description: "躯干稳定，肩膀自然下沉。",
        source: seatedCableRow01Setup,
      },
      {
        id: "drive",
        label: "后拉",
        description: "肘部向后，肩胛向中间收拢。",
        source: seatedCableRow02Drive,
      },
      {
        id: "finish",
        label: "收紧",
        description: "握把靠近身体，避免大幅后仰。",
        source: seatedCableRow03Finish,
      },
    ],
  },
  CABLE_HIGH_ROW: {
    primaryRef: "asset://exercise-guides/cable-high-row-01-setup.jpg",
    stages: [
      {
        id: "setup",
        label: "伸臂",
        description: "躯干稳定，肩膀自然下沉。",
        source: cableHighRow01Setup,
      },
      {
        id: "drive",
        label: "后拉",
        description: "肘部向后，肩胛向中间收拢。",
        source: cableHighRow02Drive,
      },
      {
        id: "finish",
        label: "收紧",
        description: "握把靠近身体，避免大幅后仰。",
        source: cableHighRow03Finish,
      },
    ],
  },
  CABLE_SINGLE_ARM_ROW: {
    primaryRef: "asset://exercise-guides/cable-single-arm-row-01-setup.jpg",
    stages: [
      {
        id: "setup",
        label: "伸臂",
        description: "躯干稳定，肩膀自然下沉。",
        source: cableSingleArmRow01Setup,
      },
      {
        id: "drive",
        label: "后拉",
        description: "肘部向后，肩胛向中间收拢。",
        source: cableSingleArmRow02Drive,
      },
      {
        id: "finish",
        label: "收紧",
        description: "握把靠近身体，避免大幅后仰。",
        source: cableSingleArmRow03Finish,
      },
    ],
  },
  DUMBBELL_OVERHEAD_PRESS: {
    primaryRef: "asset://exercise-guides/dumbbell-overhead-press-01-setup.jpg",
    stages: [
      {
        id: "setup",
        label: "肩前",
        description: "核心收紧，负重稳定在肩部附近。",
        source: dumbbellOverheadPress01Setup,
      },
      {
        id: "drive",
        label: "推举",
        description: "沿头部两侧向上推，避免腰部后仰。",
        source: dumbbellOverheadPress02Drive,
      },
      {
        id: "finish",
        label: "顶端",
        description: "负重位于身体上方，肩颈保持放松。",
        source: dumbbellOverheadPress03Finish,
      },
    ],
  },
  SEATED_DUMBBELL_PRESS: {
    primaryRef: "asset://exercise-guides/seated-dumbbell-press-01-setup.jpg",
    stages: [
      {
        id: "setup",
        label: "肩前",
        description: "核心收紧，负重稳定在肩部附近。",
        source: seatedDumbbellPress01Setup,
      },
      {
        id: "drive",
        label: "推举",
        description: "沿头部两侧向上推，避免腰部后仰。",
        source: seatedDumbbellPress02Drive,
      },
      {
        id: "finish",
        label: "顶端",
        description: "负重位于身体上方，肩颈保持放松。",
        source: seatedDumbbellPress03Finish,
      },
    ],
  },
  SINGLE_ARM_DUMBBELL_PRESS: {
    primaryRef: "asset://exercise-guides/single-arm-dumbbell-press-01-setup.jpg",
    stages: [
      {
        id: "setup",
        label: "肩前",
        description: "核心收紧，负重稳定在肩部附近。",
        source: singleArmDumbbellPress01Setup,
      },
      {
        id: "drive",
        label: "推举",
        description: "沿头部两侧向上推，避免腰部后仰。",
        source: singleArmDumbbellPress02Drive,
      },
      {
        id: "finish",
        label: "顶端",
        description: "负重位于身体上方，肩颈保持放松。",
        source: singleArmDumbbellPress03Finish,
      },
    ],
  },
  LAT_PULLDOWN: {
    primaryRef: "asset://exercise-guides/lat-pulldown-01-setup.jpg",
    stages: [
      {
        id: "setup",
        label: "伸展",
        description: "坐稳并保持胸廓自然。",
        source: latPulldown01Setup,
      },
      {
        id: "drive",
        label: "下拉",
        description: "肘部向下，握把朝上胸移动。",
        source: latPulldown02Drive,
      },
      {
        id: "finish",
        label: "收紧",
        description: "肩胛下沉，不把握把拉到颈后。",
        source: latPulldown03Finish,
      },
    ],
  },
  CABLE_STRAIGHT_ARM_PULLDOWN: {
    primaryRef: "asset://exercise-guides/cable-straight-arm-pulldown-01-setup.jpg",
    stages: [
      {
        id: "setup",
        label: "举臂",
        description: "手臂接近伸直，躯干保持稳定。",
        source: cableStraightArmPulldown01Setup,
      },
      {
        id: "drive",
        label: "下压",
        description: "以肩关节为轴向下压握把。",
        source: cableStraightArmPulldown02Drive,
      },
      {
        id: "finish",
        label: "到腿侧",
        description: "背部收紧，避免摆动借力。",
        source: cableStraightArmPulldown03Finish,
      },
    ],
  },
  NEUTRAL_GRIP_PULLDOWN: {
    primaryRef: "asset://exercise-guides/neutral-grip-pulldown-01-setup.jpg",
    stages: [
      {
        id: "setup",
        label: "伸展",
        description: "坐稳并保持胸廓自然。",
        source: neutralGripPulldown01Setup,
      },
      {
        id: "drive",
        label: "下拉",
        description: "肘部向下，握把朝上胸移动。",
        source: neutralGripPulldown02Drive,
      },
      {
        id: "finish",
        label: "收紧",
        description: "肩胛下沉，不把握把拉到颈后。",
        source: neutralGripPulldown03Finish,
      },
    ],
  },
  PRONE_W_RAISE: {
    primaryRef: "asset://exercise-guides/prone-w-raise-01-setup.jpg",
    stages: [
      {
        id: "setup",
        label: "俯卧",
        description: "颈部放松，额头轻靠支撑。",
        source: proneWRaise01Setup,
      },
      {
        id: "drive",
        label: "抬臂",
        description: "肩胛先稳定，再小幅抬起手臂。",
        source: proneWRaise02Drive,
      },
      {
        id: "finish",
        label: "收紧",
        description: "保持 W 或 Y 形，不耸肩。",
        source: proneWRaise03Finish,
      },
    ],
  },
  PRONE_Y_RAISE: {
    primaryRef: "asset://exercise-guides/prone-y-raise-01-setup.jpg",
    stages: [
      {
        id: "setup",
        label: "俯卧",
        description: "颈部放松，额头轻靠支撑。",
        source: proneYRaise01Setup,
      },
      {
        id: "drive",
        label: "抬臂",
        description: "肩胛先稳定，再小幅抬起手臂。",
        source: proneYRaise02Drive,
      },
      {
        id: "finish",
        label: "收紧",
        description: "保持 W 或 Y 形，不耸肩。",
        source: proneYRaise03Finish,
      },
    ],
  },
  DEAD_BUG: {
    primaryRef: "asset://exercise-guides/dead-bug-01-setup.jpg",
    stages: [
      {
        id: "setup",
        label: "准备",
        description: "仰卧抬起手脚，腰背保持稳定。",
        source: deadBug01Setup,
      },
      {
        id: "extend",
        label: "伸展",
        description: "对侧手臂和腿缓慢远离身体。",
        source: deadBug02Extend,
      },
      {
        id: "control",
        label: "控制",
        description: "继续伸展，同时保持腰背贴稳。",
        source: deadBug03Control,
      },
      {
        id: "finish",
        label: "到位",
        description: "在躯干不晃动的范围内停住。",
        source: deadBug04Finish,
      },
    ],
  },
  BIRD_DOG: {
    primaryRef: "asset://exercise-guides/bird-dog-01-setup.jpg",
    stages: [
      {
        id: "setup",
        label: "四点支撑",
        description: "双手双膝压稳，背部保持平直。",
        source: birdDog01Setup,
      },
      {
        id: "extend",
        label: "开始伸展",
        description: "对侧手脚缓慢离地。",
        source: birdDog02Extend,
      },
      {
        id: "control",
        label: "继续伸展",
        description: "髋部保持水平，避免身体旋转。",
        source: birdDog03Control,
      },
      {
        id: "finish",
        label: "伸直到位",
        description: "手脚延伸，躯干仍然稳定。",
        source: birdDog04Finish,
      },
    ],
  },
  PLANK: {
    primaryRef: "asset://exercise-guides/plank-01-setup.jpg",
    stages: [
      {
        id: "setup",
        label: "支撑定位",
        description: "前臂和脚尖压稳，身体接近直线。",
        source: plank01Setup,
      },
      {
        id: "hold",
        label: "稳定保持",
        description: "收紧腹部并自然呼吸，不塌腰。",
        source: plank02Hold,
      },
    ],
  },
} as const

export const staticSourcesByAssetRef = {
  "asset://exercise-guides/goblet-squat-01-setup.jpg": gobletSquat01Setup,
  "asset://exercise-guides/goblet-squat-02-drive.jpg": gobletSquat02Drive,
  "asset://exercise-guides/goblet-squat-03-finish.jpg": gobletSquat03Finish,
  "asset://exercise-guides/dumbbell-front-squat-01-setup.jpg": dumbbellFrontSquat01Setup,
  "asset://exercise-guides/dumbbell-front-squat-02-drive.jpg": dumbbellFrontSquat02Drive,
  "asset://exercise-guides/dumbbell-front-squat-03-finish.jpg": dumbbellFrontSquat03Finish,
  "asset://exercise-guides/bodyweight-squat-01-setup.jpg": bodyweightSquat01Setup,
  "asset://exercise-guides/bodyweight-squat-02-drive.jpg": bodyweightSquat02Drive,
  "asset://exercise-guides/bodyweight-squat-03-finish.jpg": bodyweightSquat03Finish,
  "asset://exercise-guides/dumbbell-romanian-deadlift-01-setup.jpg": dumbbellRomanianDeadlift01Setup,
  "asset://exercise-guides/dumbbell-romanian-deadlift-02-drive.jpg": dumbbellRomanianDeadlift02Drive,
  "asset://exercise-guides/dumbbell-romanian-deadlift-03-finish.jpg": dumbbellRomanianDeadlift03Finish,
  "asset://exercise-guides/dumbbell-deadlift-01-setup.jpg": dumbbellDeadlift01Setup,
  "asset://exercise-guides/dumbbell-deadlift-02-drive.jpg": dumbbellDeadlift02Drive,
  "asset://exercise-guides/dumbbell-deadlift-03-finish.jpg": dumbbellDeadlift03Finish,
  "asset://exercise-guides/bodyweight-hip-hinge-01-setup.jpg": bodyweightHipHinge01Setup,
  "asset://exercise-guides/bodyweight-hip-hinge-02-drive.jpg": bodyweightHipHinge02Drive,
  "asset://exercise-guides/bodyweight-hip-hinge-03-finish.jpg": bodyweightHipHinge03Finish,
  "asset://exercise-guides/dumbbell-bench-press-01-setup.jpg": dumbbellBenchPress01Setup,
  "asset://exercise-guides/dumbbell-bench-press-02-drive.jpg": dumbbellBenchPress02Drive,
  "asset://exercise-guides/dumbbell-bench-press-03-finish.jpg": dumbbellBenchPress03Finish,
  "asset://exercise-guides/dumbbell-floor-press-01-setup.jpg": dumbbellFloorPress01Setup,
  "asset://exercise-guides/dumbbell-floor-press-02-drive.jpg": dumbbellFloorPress02Drive,
  "asset://exercise-guides/dumbbell-floor-press-03-finish.jpg": dumbbellFloorPress03Finish,
  "asset://exercise-guides/incline-push-up-01-setup.jpg": inclinePushUp01Setup,
  "asset://exercise-guides/incline-push-up-02-drive.jpg": inclinePushUp02Drive,
  "asset://exercise-guides/incline-push-up-03-finish.jpg": inclinePushUp03Finish,
  "asset://exercise-guides/seated-cable-row-01-setup.jpg": seatedCableRow01Setup,
  "asset://exercise-guides/seated-cable-row-02-drive.jpg": seatedCableRow02Drive,
  "asset://exercise-guides/seated-cable-row-03-finish.jpg": seatedCableRow03Finish,
  "asset://exercise-guides/cable-high-row-01-setup.jpg": cableHighRow01Setup,
  "asset://exercise-guides/cable-high-row-02-drive.jpg": cableHighRow02Drive,
  "asset://exercise-guides/cable-high-row-03-finish.jpg": cableHighRow03Finish,
  "asset://exercise-guides/cable-single-arm-row-01-setup.jpg": cableSingleArmRow01Setup,
  "asset://exercise-guides/cable-single-arm-row-02-drive.jpg": cableSingleArmRow02Drive,
  "asset://exercise-guides/cable-single-arm-row-03-finish.jpg": cableSingleArmRow03Finish,
  "asset://exercise-guides/dumbbell-overhead-press-01-setup.jpg": dumbbellOverheadPress01Setup,
  "asset://exercise-guides/dumbbell-overhead-press-02-drive.jpg": dumbbellOverheadPress02Drive,
  "asset://exercise-guides/dumbbell-overhead-press-03-finish.jpg": dumbbellOverheadPress03Finish,
  "asset://exercise-guides/seated-dumbbell-press-01-setup.jpg": seatedDumbbellPress01Setup,
  "asset://exercise-guides/seated-dumbbell-press-02-drive.jpg": seatedDumbbellPress02Drive,
  "asset://exercise-guides/seated-dumbbell-press-03-finish.jpg": seatedDumbbellPress03Finish,
  "asset://exercise-guides/single-arm-dumbbell-press-01-setup.jpg": singleArmDumbbellPress01Setup,
  "asset://exercise-guides/single-arm-dumbbell-press-02-drive.jpg": singleArmDumbbellPress02Drive,
  "asset://exercise-guides/single-arm-dumbbell-press-03-finish.jpg": singleArmDumbbellPress03Finish,
  "asset://exercise-guides/lat-pulldown-01-setup.jpg": latPulldown01Setup,
  "asset://exercise-guides/lat-pulldown-02-drive.jpg": latPulldown02Drive,
  "asset://exercise-guides/lat-pulldown-03-finish.jpg": latPulldown03Finish,
  "asset://exercise-guides/cable-straight-arm-pulldown-01-setup.jpg": cableStraightArmPulldown01Setup,
  "asset://exercise-guides/cable-straight-arm-pulldown-02-drive.jpg": cableStraightArmPulldown02Drive,
  "asset://exercise-guides/cable-straight-arm-pulldown-03-finish.jpg": cableStraightArmPulldown03Finish,
  "asset://exercise-guides/neutral-grip-pulldown-01-setup.jpg": neutralGripPulldown01Setup,
  "asset://exercise-guides/neutral-grip-pulldown-02-drive.jpg": neutralGripPulldown02Drive,
  "asset://exercise-guides/neutral-grip-pulldown-03-finish.jpg": neutralGripPulldown03Finish,
  "asset://exercise-guides/prone-w-raise-01-setup.jpg": proneWRaise01Setup,
  "asset://exercise-guides/prone-w-raise-02-drive.jpg": proneWRaise02Drive,
  "asset://exercise-guides/prone-w-raise-03-finish.jpg": proneWRaise03Finish,
  "asset://exercise-guides/prone-y-raise-01-setup.jpg": proneYRaise01Setup,
  "asset://exercise-guides/prone-y-raise-02-drive.jpg": proneYRaise02Drive,
  "asset://exercise-guides/prone-y-raise-03-finish.jpg": proneYRaise03Finish,
  "asset://exercise-guides/dead-bug-01-setup.jpg": deadBug01Setup,
  "asset://exercise-guides/dead-bug-02-extend.jpg": deadBug02Extend,
  "asset://exercise-guides/dead-bug-03-control.jpg": deadBug03Control,
  "asset://exercise-guides/dead-bug-04-finish.jpg": deadBug04Finish,
  "asset://exercise-guides/bird-dog-01-setup.jpg": birdDog01Setup,
  "asset://exercise-guides/bird-dog-02-extend.jpg": birdDog02Extend,
  "asset://exercise-guides/bird-dog-03-control.jpg": birdDog03Control,
  "asset://exercise-guides/bird-dog-04-finish.jpg": birdDog04Finish,
  "asset://exercise-guides/plank-01-setup.jpg": plank01Setup,
  "asset://exercise-guides/plank-02-hold.jpg": plank02Hold,
} as const
