/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/wechat/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["loginWithWechatCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refreshSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getProfile"];
        put: operations["updateProfile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profile/equipment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getEquipmentProfile"];
        put: operations["updateEquipmentProfile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profile/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getExercisePreferences"];
        put: operations["updateExercisePreferences"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exercises": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listExercises"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exercises/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getExercise"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plan-templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listPlanTemplates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description 规则引擎生成合法结构和全部关键数字；AI 解释允许为空、异步或降级。 */
        post: operations["generatePlanCandidates"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["validatePlanDraft"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createInitialPlan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getActivePlan"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/{planId}/versions/{versionNo}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPlanVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/{planId}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createPlanVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/{planId}/rebalance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description 只返回预览；USER_LOCKED 字段不得被静默覆盖。 */
        post: operations["previewPlanRebalance"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workouts/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTodayWorkout"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workout-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listWorkoutSessions"];
        put?: never;
        post: operations["startWorkoutSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workout-sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getWorkoutSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workout-sessions/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateWorkoutSessionStatus"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workout-sessions/{id}/exercises/{exerciseId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateWorkoutSessionExercise"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workout-sessions/{id}/sets/{clientSetKey}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["upsertWorkoutSet"];
        post?: never;
        delete: operations["deleteUnfinishedWorkoutSet"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workout-sessions/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["completeWorkoutSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sync/workout-operations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description 每项独立返回 APPLIED、DUPLICATE、CONFLICT 或 REJECTED。 */
        post: operations["syncWorkoutOperations"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sync/conflicts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listSyncConflicts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sync/conflicts/{id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resolveSyncConflict"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workout-sessions/{id}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getWorkoutSessionSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/progress/exercises/{exerciseId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getExerciseProgress"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/progression-recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listProgressionRecommendations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/progression-recommendations/{id}/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description USER_LOCKED 重量只允许提示；应用前必须显式确认并创建新计划版本。 */
        post: operations["applyProgressionRecommendation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/progression-recommendations/{id}/dismiss": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["dismissProgressionRecommendation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/plan-explanations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description 仅请求解释，不得改变规则生成的关键数字。 */
        post: operations["requestPlanExplanation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/workout-summaries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description 仅请求解释性总结，规则结论保持权威。 */
        post: operations["requestWorkoutSummary"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/privacy/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getOrStartPrivacyExport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/privacy/deletion-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createPrivacyDeletionRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/privacy/deletion-requests/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPrivacyDeletionRequest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiResponse: {
            data: unknown;
            meta: components["schemas"]["ResponseMeta"];
        };
        ApiError: {
            code: components["schemas"]["ErrorCode"];
            message: string;
            fieldErrors: components["schemas"]["FieldError"][];
            details: {
                [key: string]: unknown;
            };
            retryable: boolean;
        };
        ApiErrorResponse: {
            error: components["schemas"]["ApiError"];
            meta: components["schemas"]["ErrorMeta"];
        };
        FieldError: {
            path: string;
            code: string;
            parameters?: {
                [key: string]: unknown;
            };
        };
        ResponseMeta: {
            requestId: components["schemas"]["RequestId"];
            serverTime: components["schemas"]["UtcDateTime"];
        };
        ErrorMeta: {
            requestId: components["schemas"]["RequestId"];
        };
        RequestId: string;
        /**
         * Format: date-time
         * @example 2026-07-23T10:30:00Z
         */
        UtcDateTime: string;
        /** Format: int64 */
        ExpectedVersion: number;
        /** @enum {string} */
        ErrorCode: "VALIDATION_FAILED" | "AUTHENTICATION_REQUIRED" | "ACCESS_DENIED" | "RESOURCE_NOT_FOUND" | "VERSION_CONFLICT" | "IDEMPOTENCY_KEY_REUSED" | "PLAN_VALIDATION_FAILED" | "SESSION_ALREADY_TERMINAL" | "SYNC_CONFLICT" | "RATE_LIMITED" | "INTERNAL_ERROR";
        Weight: {
            value: number;
            unit: components["schemas"]["WeightUnit"];
            equipmentProfileId?: string;
        };
        /**
         * @description P0 仅接受 KG；不得隐式换算或启用 LB。
         * @enum {string}
         */
        WeightUnit: "KG";
        RuleReference: {
            ruleVersion: string;
            templateVersion: string;
            contentVersion: string;
        };
        /** @enum {string} */
        ValidationSeverity: "INFO" | "WARNING" | "ERROR";
        /** @enum {string} */
        AiExplanationStatus: "READY" | "PENDING" | "DEGRADED";
        /** @enum {string} */
        WeightStatus: "KNOWN" | "NEEDS_CALIBRATION" | "BODYWEIGHT";
        /** @enum {string} */
        LockStatus: "USER_LOCKED" | "RULE_LOCKED" | "UNLOCKED";
        /** @enum {string} */
        SessionStatus: "CREATED" | "IN_PROGRESS" | "PAUSED" | "COMPLETING" | "COMPLETED" | "ABORTED";
        /** @enum {string} */
        SyncOperationStatus: "APPLIED" | "DUPLICATE" | "CONFLICT" | "REJECTED";
        /** @enum {string} */
        ProgressionDecision: "INCREASE" | "KEEP" | "REDUCE" | "REVIEW";
        WechatLoginRequest: {
            /** @description 微信临时登录码，不得写入日志或持久化。 */
            code: string;
        };
        RefreshSessionRequest: {
            refreshToken: string;
        };
        /** @enum {string} */
        ExperienceLevel: "BEGINNER" | "INTERMEDIATE" | "ADVANCED";
        /** @enum {string} */
        FitnessGoal: "STRENGTH" | "HYPERTROPHY" | "GENERAL_FITNESS";
        /** @enum {string} */
        TrainingLocation: "HOME" | "GYM" | "OTHER";
        UserProfile: {
            experience: components["schemas"]["ExperienceLevel"];
            goal: components["schemas"]["FitnessGoal"];
            weeklyFrequency: number;
            /** @enum {integer} */
            sessionMinutes: 30 | 45 | 60 | 75 | 90;
            location: components["schemas"]["TrainingLocation"];
            version: components["schemas"]["ExpectedVersion"];
        };
        UserProfileResponse: {
            data: components["schemas"]["UserProfile"];
            meta: components["schemas"]["ResponseMeta"];
        };
        UpdateProfileRequest: {
            experience: components["schemas"]["ExperienceLevel"];
            goal: components["schemas"]["FitnessGoal"];
            weeklyFrequency: number;
            /** @enum {integer} */
            sessionMinutes: 30 | 45 | 60 | 75 | 90;
            location: components["schemas"]["TrainingLocation"];
            expectedVersion: components["schemas"]["ExpectedVersion"];
        };
        EquipmentItem: {
            /**
             * Format: uuid
             * @description 客户端离线稳定键；服务端内部 user_equipment.id 不对外开放。
             */
            clientEquipmentKey: string;
            equipmentType: string;
            minIncrement: components["schemas"]["Weight"];
            availableLevels: components["schemas"]["Weight"][];
        };
        EquipmentProfile: {
            items: components["schemas"]["EquipmentItem"][];
            version: components["schemas"]["ExpectedVersion"];
        };
        EquipmentProfileResponse: {
            data: components["schemas"]["EquipmentProfile"];
            meta: components["schemas"]["ResponseMeta"];
        };
        EquipmentWeightInput: {
            value: number;
            unit: components["schemas"]["WeightUnit"];
        };
        EquipmentItemRequest: {
            /**
             * Format: uuid
             * @description 客户端离线稳定键；服务端内部 user_equipment.id 不对外开放。
             */
            clientEquipmentKey: string;
            equipmentType: string;
            minIncrement: components["schemas"]["EquipmentWeightInput"];
            availableLevels: components["schemas"]["EquipmentWeightInput"][];
        };
        UpdateEquipmentRequest: {
            items: components["schemas"]["EquipmentItemRequest"][];
            expectedVersion: components["schemas"]["ExpectedVersion"];
        };
        ExercisePreference: {
            /** Format: uuid */
            exerciseId: string;
            /** @enum {string} */
            preferenceType: "PREFERRED" | "EXCLUDED";
        };
        PreferenceProfile: {
            items: components["schemas"]["ExercisePreference"][];
            version: components["schemas"]["ExpectedVersion"];
        };
        PreferenceProfileResponse: {
            data: components["schemas"]["PreferenceProfile"];
            meta: components["schemas"]["ResponseMeta"];
        };
        UpdatePreferencesRequest: {
            items: components["schemas"]["ExercisePreference"][];
            expectedVersion: components["schemas"]["ExpectedVersion"];
        };
        PlanCandidateRequest: {
            profileVersion: components["schemas"]["ExpectedVersion"];
            lockedFields?: {
                [key: string]: unknown;
            };
        };
        PlanDraft: {
            days: {
                [key: string]: unknown;
            }[];
            locks: {
                [key: string]: components["schemas"]["LockStatus"];
            };
        };
        ValidatePlanRequest: {
            plan: components["schemas"]["PlanDraft"];
            ruleReference: components["schemas"]["RuleReference"];
        };
        CreatePlanRequest: {
            candidateId: string;
        };
        CreatePlanVersionRequest: {
            plan: components["schemas"]["PlanDraft"];
            expectedVersion: components["schemas"]["ExpectedVersion"];
        };
        RebalancePlanRequest: {
            expectedVersion: components["schemas"]["ExpectedVersion"];
            lockedFields: {
                [key: string]: unknown;
            };
        };
        StartWorkoutSessionRequest: {
            clientSessionKey: string;
            planId: string;
            planVersionNo: number;
            planDayId: string;
        };
        UpdateSessionStatusRequest: {
            status: components["schemas"]["SessionStatus"];
            expectedVersion: components["schemas"]["ExpectedVersion"];
        };
        UpdateSessionExerciseRequest: {
            /** @enum {string} */
            action: "SKIP" | "REPLACE" | "COMPLETE";
            replacementExerciseId?: string;
            expectedVersion: components["schemas"]["ExpectedVersion"];
        };
        /** @enum {string} */
        SetType: "WARMUP" | "WORK" | "EXTRA";
        SetTarget: {
            weight: components["schemas"]["Weight"];
            reps: number;
        };
        /** @enum {string} */
        CompletionStatus: "PLANNED" | "COMPLETED" | "SKIPPED";
        UpsertSetRequest: {
            clientOperationSeq: number;
            setType: components["schemas"]["SetType"];
            setOrder: number;
            target: components["schemas"]["SetTarget"];
            actual: components["schemas"]["SetTarget"];
            remainingReps?: number;
            completionStatus: components["schemas"]["CompletionStatus"];
            completedAt?: components["schemas"]["UtcDateTime"];
            expectedSessionVersion: components["schemas"]["ExpectedVersion"];
        };
        DeleteSetRequest: {
            expectedSessionVersion: components["schemas"]["ExpectedVersion"];
        };
        CompleteSessionRequest: {
            expectedVersion: components["schemas"]["ExpectedVersion"];
            /** @enum {string} */
            completionType: "FULL" | "EARLY_END";
        };
        SyncOperation: {
            clientOperationSeq: number;
            operationType: string;
            clientKey: string;
            payload: {
                [key: string]: unknown;
            };
        };
        SyncWorkoutOperationsRequest: {
            operations: components["schemas"]["SyncOperation"][];
        };
        ResolveSyncConflictRequest: {
            /** @enum {string} */
            resolution: "KEEP_LOCAL" | "KEEP_SERVER" | "KEEP_BOTH";
            expectedVersion: components["schemas"]["ExpectedVersion"];
        };
        /** @enum {string} */
        RecommendationStatus: "PENDING" | "APPLIED" | "DISMISSED";
        ApplyRecommendationRequest: {
            expectedVersion: components["schemas"]["ExpectedVersion"];
            acceptedWeight?: components["schemas"]["Weight"];
        };
        DismissRecommendationRequest: {
            reasonCode?: string;
        };
        AiPlanExplanationRequest: {
            candidateId: string;
        };
        AiWorkoutSummaryRequest: {
            workoutSessionId: string;
        };
        CreateDeletionRequest: {
            /** @enum {string} */
            confirmation: "DELETE_MY_DATA";
        };
    };
    responses: {
        /** @description 成功 */
        Success: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiResponse"];
            };
        };
        /** @description 请求不合法 */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiErrorResponse"];
            };
        };
        /** @description 未认证或会话失效 */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiErrorResponse"];
            };
        };
        /** @description 资源不存在或不属于当前用户 */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiErrorResponse"];
            };
        };
        /** @description expectedVersion 与当前资源版本不一致，错误码为 VERSION_CONFLICT。 */
        VersionConflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiErrorResponse"];
            };
        };
        /** @description 统一错误响应 */
        DefaultError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiErrorResponse"];
            };
        };
    };
    parameters: {
        IdPath: string;
        PlanIdPath: string;
        VersionNoPath: number;
        ExerciseIdPath: string;
        ClientSetKeyPath: string;
        Cursor: string;
        /** @description 在已认证用户和操作类型范围内唯一；同键不同 payload 将被拒绝。 */
        IdempotencyKey: string;
    };
    requestBodies: {
        WechatLogin: {
            content: {
                "application/json": components["schemas"]["WechatLoginRequest"];
            };
        };
        RefreshSession: {
            content: {
                "application/json": components["schemas"]["RefreshSessionRequest"];
            };
        };
        ProfileUpdate: {
            content: {
                "application/json": components["schemas"]["UpdateProfileRequest"];
            };
        };
        EquipmentUpdate: {
            content: {
                "application/json": components["schemas"]["UpdateEquipmentRequest"];
            };
        };
        PreferencesUpdate: {
            content: {
                "application/json": components["schemas"]["UpdatePreferencesRequest"];
            };
        };
        PlanCandidates: {
            content: {
                "application/json": components["schemas"]["PlanCandidateRequest"];
            };
        };
        PlanValidation: {
            content: {
                "application/json": components["schemas"]["ValidatePlanRequest"];
            };
        };
        PlanCreation: {
            content: {
                "application/json": components["schemas"]["CreatePlanRequest"];
            };
        };
        PlanVersionCreation: {
            content: {
                "application/json": components["schemas"]["CreatePlanVersionRequest"];
            };
        };
        PlanRebalance: {
            content: {
                "application/json": components["schemas"]["RebalancePlanRequest"];
            };
        };
        WorkoutSessionStart: {
            content: {
                "application/json": components["schemas"]["StartWorkoutSessionRequest"];
            };
        };
        WorkoutStatusUpdate: {
            content: {
                "application/json": components["schemas"]["UpdateSessionStatusRequest"];
            };
        };
        WorkoutExerciseUpdate: {
            content: {
                "application/json": components["schemas"]["UpdateSessionExerciseRequest"];
            };
        };
        SetUpsert: {
            content: {
                "application/json": components["schemas"]["UpsertSetRequest"];
            };
        };
        SetDeletion: {
            content: {
                "application/json": components["schemas"]["DeleteSetRequest"];
            };
        };
        WorkoutCompletion: {
            content: {
                "application/json": components["schemas"]["CompleteSessionRequest"];
            };
        };
        WorkoutOperationSync: {
            content: {
                "application/json": components["schemas"]["SyncWorkoutOperationsRequest"];
            };
        };
        SyncConflictResolution: {
            content: {
                "application/json": components["schemas"]["ResolveSyncConflictRequest"];
            };
        };
        RecommendationApply: {
            content: {
                "application/json": components["schemas"]["ApplyRecommendationRequest"];
            };
        };
        RecommendationDismiss: {
            content: {
                "application/json": components["schemas"]["DismissRecommendationRequest"];
            };
        };
        AiPlanExplanation: {
            content: {
                "application/json": components["schemas"]["AiPlanExplanationRequest"];
            };
        };
        AiWorkoutSummary: {
            content: {
                "application/json": components["schemas"]["AiWorkoutSummaryRequest"];
            };
        };
        PrivacyDeletion: {
            content: {
                "application/json": components["schemas"]["CreateDeletionRequest"];
            };
        };
    };
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    loginWithWechatCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["WechatLogin"];
        responses: {
            200: components["responses"]["Success"];
            400: components["responses"]["BadRequest"];
            default: components["responses"]["DefaultError"];
        };
    };
    refreshSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["RefreshSession"];
        responses: {
            200: components["responses"]["Success"];
            401: components["responses"]["Unauthorized"];
            default: components["responses"]["DefaultError"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
            401: components["responses"]["Unauthorized"];
            default: components["responses"]["DefaultError"];
        };
    };
    getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 当前用户档案 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            default: components["responses"]["DefaultError"];
        };
    };
    updateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["ProfileUpdate"];
        responses: {
            /** @description 更新后的当前用户档案 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileResponse"];
                };
            };
            409: components["responses"]["VersionConflict"];
            default: components["responses"]["DefaultError"];
        };
    };
    getEquipmentProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 当前用户器械档案 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EquipmentProfileResponse"];
                };
            };
            default: components["responses"]["DefaultError"];
        };
    };
    updateEquipmentProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["EquipmentUpdate"];
        responses: {
            /** @description 更新后的当前用户器械档案 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EquipmentProfileResponse"];
                };
            };
            409: components["responses"]["VersionConflict"];
            default: components["responses"]["DefaultError"];
        };
    };
    getExercisePreferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 当前用户动作偏好 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreferenceProfileResponse"];
                };
            };
            default: components["responses"]["DefaultError"];
        };
    };
    updateExercisePreferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["PreferencesUpdate"];
        responses: {
            /** @description 更新后的当前用户动作偏好 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreferenceProfileResponse"];
                };
            };
            409: components["responses"]["VersionConflict"];
            default: components["responses"]["DefaultError"];
        };
    };
    listExercises: {
        parameters: {
            query?: {
                equipmentType?: string;
                movementPattern?: string;
                muscleGroup?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
            default: components["responses"]["DefaultError"];
        };
    };
    getExercise: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["DefaultError"];
        };
    };
    listPlanTemplates: {
        parameters: {
            query?: {
                weeklyFrequency?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
            default: components["responses"]["DefaultError"];
        };
    };
    generatePlanCandidates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["PlanCandidates"];
        responses: {
            200: components["responses"]["Success"];
            400: components["responses"]["BadRequest"];
            default: components["responses"]["DefaultError"];
        };
    };
    validatePlanDraft: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["PlanValidation"];
        responses: {
            200: components["responses"]["Success"];
            400: components["responses"]["BadRequest"];
            default: components["responses"]["DefaultError"];
        };
    };
    createInitialPlan: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["PlanCreation"];
        responses: {
            201: components["responses"]["Success"];
            400: components["responses"]["BadRequest"];
            default: components["responses"]["DefaultError"];
        };
    };
    getActivePlan: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["DefaultError"];
        };
    };
    getPlanVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: components["parameters"]["PlanIdPath"];
                versionNo: components["parameters"]["VersionNoPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["DefaultError"];
        };
    };
    createPlanVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: components["parameters"]["PlanIdPath"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["PlanVersionCreation"];
        responses: {
            201: components["responses"]["Success"];
            409: components["responses"]["VersionConflict"];
            default: components["responses"]["DefaultError"];
        };
    };
    previewPlanRebalance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: components["parameters"]["PlanIdPath"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["PlanRebalance"];
        responses: {
            200: components["responses"]["Success"];
            409: components["responses"]["VersionConflict"];
            default: components["responses"]["DefaultError"];
        };
    };
    getTodayWorkout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
            default: components["responses"]["DefaultError"];
        };
    };
    listWorkoutSessions: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
            default: components["responses"]["DefaultError"];
        };
    };
    startWorkoutSession: {
        parameters: {
            query?: never;
            header: {
                /** @description 在已认证用户和操作类型范围内唯一；同键不同 payload 将被拒绝。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["WorkoutSessionStart"];
        responses: {
            201: components["responses"]["Success"];
            default: components["responses"]["DefaultError"];
        };
    };
    getWorkoutSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["DefaultError"];
        };
    };
    updateWorkoutSessionStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["WorkoutStatusUpdate"];
        responses: {
            200: components["responses"]["Success"];
            409: components["responses"]["VersionConflict"];
            default: components["responses"]["DefaultError"];
        };
    };
    updateWorkoutSessionExercise: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
                exerciseId: components["parameters"]["ExerciseIdPath"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["WorkoutExerciseUpdate"];
        responses: {
            200: components["responses"]["Success"];
            409: components["responses"]["VersionConflict"];
            default: components["responses"]["DefaultError"];
        };
    };
    upsertWorkoutSet: {
        parameters: {
            query?: never;
            header: {
                /** @description 在已认证用户和操作类型范围内唯一；同键不同 payload 将被拒绝。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                id: components["parameters"]["IdPath"];
                clientSetKey: components["parameters"]["ClientSetKeyPath"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["SetUpsert"];
        responses: {
            200: components["responses"]["Success"];
            409: components["responses"]["VersionConflict"];
            default: components["responses"]["DefaultError"];
        };
    };
    deleteUnfinishedWorkoutSet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
                clientSetKey: components["parameters"]["ClientSetKeyPath"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["SetDeletion"];
        responses: {
            200: components["responses"]["Success"];
            409: components["responses"]["VersionConflict"];
            default: components["responses"]["DefaultError"];
        };
    };
    completeWorkoutSession: {
        parameters: {
            query?: never;
            header: {
                /** @description 在已认证用户和操作类型范围内唯一；同键不同 payload 将被拒绝。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["WorkoutCompletion"];
        responses: {
            200: components["responses"]["Success"];
            409: components["responses"]["VersionConflict"];
            default: components["responses"]["DefaultError"];
        };
    };
    syncWorkoutOperations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["WorkoutOperationSync"];
        responses: {
            200: components["responses"]["Success"];
            default: components["responses"]["DefaultError"];
        };
    };
    listSyncConflicts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
            default: components["responses"]["DefaultError"];
        };
    };
    resolveSyncConflict: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["SyncConflictResolution"];
        responses: {
            200: components["responses"]["Success"];
            409: components["responses"]["VersionConflict"];
            default: components["responses"]["DefaultError"];
        };
    };
    getWorkoutSessionSummary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
            default: components["responses"]["DefaultError"];
        };
    };
    getExerciseProgress: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exerciseId: components["parameters"]["ExerciseIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
            default: components["responses"]["DefaultError"];
        };
    };
    listProgressionRecommendations: {
        parameters: {
            query?: {
                status?: components["schemas"]["RecommendationStatus"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
            default: components["responses"]["DefaultError"];
        };
    };
    applyProgressionRecommendation: {
        parameters: {
            query?: never;
            header: {
                /** @description 在已认证用户和操作类型范围内唯一；同键不同 payload 将被拒绝。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["RecommendationApply"];
        responses: {
            200: components["responses"]["Success"];
            409: components["responses"]["VersionConflict"];
            default: components["responses"]["DefaultError"];
        };
    };
    dismissProgressionRecommendation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["RecommendationDismiss"];
        responses: {
            200: components["responses"]["Success"];
            default: components["responses"]["DefaultError"];
        };
    };
    requestPlanExplanation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["AiPlanExplanation"];
        responses: {
            200: components["responses"]["Success"];
            default: components["responses"]["DefaultError"];
        };
    };
    requestWorkoutSummary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["AiWorkoutSummary"];
        responses: {
            200: components["responses"]["Success"];
            default: components["responses"]["DefaultError"];
        };
    };
    getOrStartPrivacyExport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
            default: components["responses"]["DefaultError"];
        };
    };
    createPrivacyDeletionRequest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["PrivacyDeletion"];
        responses: {
            201: components["responses"]["Success"];
            default: components["responses"]["DefaultError"];
        };
    };
    getPrivacyDeletionRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["DefaultError"];
        };
    };
}
