package com.aifitness.assistant.common.api;

public enum ErrorCode {
    VALIDATION_FAILED,
    AUTHENTICATION_REQUIRED,
    REAUTHENTICATION_REQUIRED,
    ACCESS_DENIED,
    RESOURCE_NOT_FOUND,
    VERSION_CONFLICT,
    IDEMPOTENCY_KEY_REUSED,
    ANOMALY_CONFIRMATION_REQUIRED,
    PLAN_VALIDATION_FAILED,
    SESSION_ALREADY_TERMINAL,
    SYNC_CONFLICT,
    RATE_LIMITED,
    INTERNAL_ERROR
}
