package com.aifitness.assistant.common.api;

public enum ErrorCode {
    VALIDATION_FAILED,
    AUTHENTICATION_REQUIRED,
    ACCESS_REVOKED,
    REAUTHENTICATION_REQUIRED,
    ACCESS_DENIED,
    RESOURCE_NOT_FOUND,
    VERSION_CONFLICT,
    IDEMPOTENCY_KEY_REUSED,
    ANOMALY_CONFIRMATION_REQUIRED,
    RECOVERY_CONFIRMATION_REQUIRED,
    ACTIVE_WORKOUT_EXISTS,
    WORKOUT_START_ALREADY_TERMINAL,
    INSUFFICIENT_REPLACEMENTS,
    PLAN_VALIDATION_FAILED,
    SESSION_ALREADY_TERMINAL,
    WORKOUT_NOT_TERMINAL,
    SYNC_CONFLICT,
    RATE_LIMITED,
    INTERNAL_ERROR
}
